### ISSUE TITLE
throttledSample

### ISSUE THREAD

**Issue by fpillet** [RxSwiftCommunity/RxSwiftExt#10]
### Name of the operator

``` swift
extension ObservableType {
  public func throttledSample(interval: RxTimeInterval, pauseInterval: RxTimeInterval = 0, scheduler: SchedulerType)
    -> Observable<E>
}
```

This operator will deliver the latest element of the source sequence at a specified interval. If the source sequence keeps sending out new elements, you are guaranteed to receive one every `interval` seconds. 

If the source sequence stops sending elements:
- if `pauseInterval` is specified and > 0, send the latest element after `pauseInterval` seconds
- if `pauseInterval` is not specified or == 0, the latest element will be sent after `interval` seconds

If no element is sent during `interval` seconds, `throttledSample` will send the first element that comes after this delay, then reset its internal timer and deliver the next latest element after `minimumInterval` seconds at the latest.
### Motivation for inclusion

This operator is what throttle should have been right from the start. The standard `throttle` operator won't deliver anything if the source sequence keeps sending new elements at intervals less than the throttle interval. What you usually want (particularly when handling UI) is a regular sample of the latest value, but no sample when there was no new value.

In some cases, for example (and typically) when processing text typed in a text field to deliver search results, you want to receive the latest typed text faster than `interval` seconds when the user stops typing. See below for details.

This operator is more complex than the average but allows modelling a finely tuned delivery of sequence elements over time.
### Example of usage

In the context of throttling a textfield to provide search results, the ideal behavior is the following:
- when the user starts typing, deliver a first sample immediately
- while the user keeps typing, update the search results every 2 seconds, that is enough
- when the user stops or pauses typing, update the search results quickly after 0.50 seconds

This behavior is what a user would expect from a search text field and can be modeled as follows:

``` swift
let latestResults : Variable<[SearchResult]> = Variable([])

self.textField.rx_text
   .throttledSample(2.0, pauseInterval: 0.3, scheduler: networkRequestsScheduler)
   .flatMapLatest { getSearchResults($0) }
   .asDriver(onErrorJustReturn: [])
   .drive(latestResults)
```

**Comment by fpillet** [comment]
Since there doesn't seem to be any contradictory discussion, I'll go ahead and approve this one.

**Comment by kzaher** [comment]
Hey @fpillet ,

we'll need to fix throttle in RxSwift repo also :) It now has debounce behavior :( 

I've checked out RxJS code

https://github.com/Reactive-Extensions/RxJS/blob/9d6ea94244c2f40a29373f9ed6b12d951d3f2238/src/modular/observable/throttle.js#L17

But it seems their throttle doesn't replay latest element after interval has passed, which is weird. I'll try to find more informations about this.

**Comment by kzaher** [comment]
We've fixed this for RxSwift 3.0.0-beta.1

**Comment by anohren** [comment]
This is exactly what I was missing when trying out Rx. 

I'm a little confused though:

> if pauseInterval is specified and > 0, send the latest element after pauseInterval seconds

- PauseInterval seconds after what? I assume since the last source sample, as opposed to since the last delivered sample (which the other `interval` pertains to)?

> If no element is sent during interval seconds, throttledSample will send the first element that comes after this delay, then reset its internal timer and deliver the next latest element after minimumInterval seconds at the latest.

- I have a hard time understanding the purpose of `minimumInterval`, and I don't see it used in the example. 
- Doesn't "at the latest" imply `maximumInterval`?

**Comment by fpillet** [comment]
>> if pauseInterval is specified and > 0, send the latest element after pauseInterval seconds

> - PauseInterval seconds after what? I assume since the last source sample, as opposed to since the last delivered sample (which the other `interval` pertains to)?

Yes after the last element emitted by the source.

> I have a hard time understanding the purpose of minimumInterval, and I don't see it used in the example.
> Doesn't "at the latest" imply maximumInterval?

What are you referring to? I only described `interval` and `pauseInterval` parameters. The example (with a search box) would be the typical use case for this operator.

**Comment by anohren** [comment]
Thank you for replying. 

I'm referring to this paragraph which mentions `minimumInterval` as though it were a property:

> If no element is sent during `interval` seconds, `throttledSample` will send the first element that comes after this delay, then reset its internal timer and deliver the next latest element after `minimumInterval` seconds at the latest.

**Comment by mcontin** [comment]
What happened to this operator? It could come in handy for buttons if I understood correctly how it works.

**Comment by fpillet** [comment]
I think nobody took the time to implement it, that's what happened :) but good reminder that we should go through the list and process the early ideas.

**Comment by freak4pc** [comment]
I'm closing this for now due to inactivity - If you have any more comments on this subject, feel free to comment or ping me directly and I'll re-open it :) Thanks !
