### ISSUE TITLE
Weakify for 'do'

### ISSUE THREAD

**Issue by hamdshah** [RxSwiftCommunity/RxSwiftExt#103]
### Name and description
Providing weak function pointer for `do` Next, Error, etc
 
### Motivation for inclusion
Currently we have `subscribeError` and `subscribeNext` for weak function reference, 
but nothing like that for `do`

### Example of use
currently for `subscribe`
`loginObservable.subscribeNext(weak: self, Login.routeTo)`

For `do` it would be something like this
`loginObservable.doNext(weak: self, Login.routeTo)`

**Comment by fpillet** [comment]
Sure, open to that! Can you send a PR for this along with tests & example Playground page ?

**Comment by hamdullahshah** [comment]
Sure, will send a request on weekend 👍🏽

**Comment by fpillet** [comment]
Thank you!

**Comment by freak4pc** [comment]
I'm closing this for now due to inactivity - If you have any more comments on this subject, feel free to comment or ping me directly and I'll re-open it :) Thanks !
