### ISSUE TITLE
Swift 4 .podspec missing Tools/curry.swift` file

### ISSUE THREAD

**Issue by zigdanis** [RxSwiftCommunity/RxSwiftExt#106]
### Name and description
RxSwiftExt.podspec for Swift 4 branch missing `Tools/curry.swift` file in it's `source_files` parameter
### Motivation for inclusion
I'm getting Error in Xcode 9 when adding RxSwiftExt to my Podfile with specified branch.
### Example of use
My Podfile looks like this:
pod 'RxSwiftExt',:git => 'https://github.com/RxSwiftCommunity/RxSwiftExt.git', :branch => 'swift4.0'
After running `pod update` command I'm getting errors in Xcode:
```
.../Pods/RxSwiftExt/Source/RxSwift/fromAsync.swift:31:49: error: use of unresolved identifier 'curry'
```

**Comment by fpillet** [comment]
Fix merged, thanks!
