### ISSUE TITLE
Is it a time to "deprecate-remove" "apply"?

### ISSUE THREAD

**Issue by nikita-leonov** [RxSwiftCommunity/RxSwiftExt#113]
There is now a `bind(to:)` custom binder in Rx with an implementation:
```
public func bind<R>(to binder: (Self) -> R) -> R {
        return binder(self)
}
```
apply's implementation is following:
```
public func apply<T>(_ transform: (Observable<Self.E>) -> Observable<T>) -> Observable<T> {
       return transform(self.asObservable())
}
```

They do the same. I assume it is a time to deprecate-remove apply to avoid naming confusion as well as minimize RxSwiftExt footprint. Deprecation-removal can be done in a following style — https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Deprecations%2BRemovals.swift

**Comment by freak4pc** [comment]
@nikita-leonov They aren't entirely the same 

1. There is a contextual different - binding to a "binder" isn't a transformation
2. bind lets you transform to any type. Apply enforces a transformation *from* `Observable<T>` *to* `Observable<T>`

```swift
let a = Observable.of("a", "b", "c")

// Bind doesn't enforce Observable<T>
// You can return a raw value, of an Observable of any type
let x = a.bind { str in
    return "abc" // x is of type String (which is pointless, since you can't observe it)
}

// y is of type Observable<Int>
let y = a.bind { str in
    return Observable.just(str.count)
}

// Returned type must be an Observable<T>
let z = a.apply { str in
    return .just("aa")
}
```

**Comment by freak4pc** [comment]
Closing due to not response from OP
