### ISSUE TITLE
map ambiguous reference in Swift 4

### ISSUE THREAD

**Issue by Gloix** [RxSwiftCommunity/RxSwiftExt#117]
I have a code that used to compile in Swift 3, but now unfortunately does not compile in Swift 4 due to an ambiguity issue.
Turns out the compiler seems to believe that I want to use the `map(to:)` method, but instead I just want the plain old `map(transform:)` from RxSwift.

This is my code (sort of) simplified:

    let filteredClBeaconStream = beaconsSource  // beaconsSource: Observable<[CLBeacon]>
        .buffer(timeSpan: 1, count: 100, scheduler: MainScheduler.instance)
        .map {(clBeaconsLists: [[CLBeacon]]) -> [CLBeacon] in
            return Array<CLBeacon>(clBeaconsLists.joined())
        } 

I know that I can just include the closure inside the parameter list of map to make the call more explicit (and indeed it works), but:

- I have called `map` everywhere in my code like that, so in order to avoid confusion I would have to change all my code, which I don't see as a viable solution.
- Why does the compiler mistakenly use RxSwiftExt's `map` method in some parts and not others. Not even an error or warning pops up regarding the ambiguity itself.

Given that `mapTo` changed to `map(to:)` and the use of a trailing closure adds ambiguity to method calls since argument labels are left out for the closure, what would be a proper solution to this?

**Comment by fpillet** [comment]
Sorry for the late reply. Did you find a solution to this? I'm looking into our options but if we don't have any, we'll fallback on the previous `mapTo` naming to avoid conflicts.

**Comment by freak4pc** [comment]
Maybe just adding mapTo as an alias, but not removing the new naming would be good. I think that's what you planned by "fallback", right?

**Comment by fpillet** [comment]
I ran tests and we indeed collide. Compiler goes to `map(to:)` when you have imported RxSwiftExt and using `map { some trailing closure }`. Looks like it's painful. If we are creating a conflict with core, my choice will always be to change our side :)

**Comment by Gloix** [comment]
@fpillet My solution for now has been to use parenthesis to explicitly state the `map` method that I want. 

It's a shame Swift has this 'flaw'.

**Comment by fpillet** [comment]
I agree. So this means that we will roll back to `mapTo` since it is not acceptable that we shadow a core operator. Thanks for the feedback
