### ISSUE TITLE
Infinity loop when using `ignoreErrors`

### ISSUE THREAD

**Issue by Sajjon** [RxSwiftCommunity/RxSwiftExt#118]
### Motivation for inclusion
The code below is a **minimum** example, so I understand it is hard to understand why I would like to cast `asSingle().asObservable()` but in my real code I have some APIs returns a Single. This `Single` is created from something that might return an optional, thus I use `Observable.from(optional: SOME_FUNCTION_RETURNING_OPTIONAL).asSingle()`

I sometimes want to emit an error, and sometimes not, based on a boolean expression. Thus I would like to use `ignoreErrors`.

### Example of use

The code below results in an infinity loop printing:
```swift
Ignoring error: `Sequence doesn't contain any elements.`
```

I do not understand why.

```swift
    let bag = DisposeBag()
    // This method creates an infinity loop when creating an Observable using `Observable.from(optional: nil)`, converting it to a Single and back to an Observable if returning `true` from `func ignoreErrors`
    func infinityLoop() {
        let value: Int? = nil // Setting non nil value does not
        let isIgnoringErrors: Bool = true // Changing this to `false` results in a single
        
        // Observable.of(value) // NO inf loop              func documentation: "This method creates a new Observable instance with a variable number of elements."
        // Observable.just(value) // NO inf loop            func documentation: "Returns an observable sequence that contains a single element."
        Observable.from(optional: value) // INFINITY LOOP   func documentation: "Converts a optional to an observable sequence"
            .asSingle()
            .asObservable()
            .ignoreErrors { print("Ignoring error: `\($0)`"); return isIgnoringErrors }
            .subscribe(onNext: { print("value: \($0)") }, onError: { print("error: \($0)") })
            .disposed(by: bag)
    }
```

Note that the code does not result in an infinity loop if I use `Observable.of(value)` or `Observable.just(value)`, it only results in an infinity loop when using `Observable.from(optional: value)`.

However, in my real world case I think that I actually need to use `Observable.from(optional` since the two other does not compile, this is the part of the real code:

```swift
protocol Cache {
    func load<C>() -> C? where C: Codable
}

protocol Persisting {
    var cache: Cache { get }
}

//MARK: Making "Persisting" protocol emit an observable "Single"
extension Persisting {
    func rxLoad<C>() -> Single<C> where C: Codable {
        return Observable.from(optional: cache.load()).asSingle().do(onNext: { print("Found in cache: `\($0)`") })
    }
}
```

Using `Observable.of(cache.load())` or `Observable.just(cache.load())` above **results in compilation error**. I get the compilation error

> Value of optional type 'C?' not unwrapped; did you mean to use '!' or '?'?

So seems like `Observable.from(optional)` is the correct method

#### Question 1:  Why does the function `infinityLoop` cause an infinity loop?
Is this expected or is it a bug?

#### Question 2:  How can I update my code in `rxLoad`?
The trait `Single` is described as 

> Emits exactly one element, or an error

Which is exactly what I want from my Persisting protocol. Perhaps I need to use an Observable?

Thanks!

**Comment by fpillet** [comment]
As explained on the Slack channel, the issue was that `Single` emits an error when no element is emitted before the sequence completes; then `ignoreErrors` does a `retry` and resubscribes, triggering an infinite loop on this empty sequence.
