### ISSUE TITLE
repeatWithBehavior shouldRepeat arg ?

### ISSUE THREAD

**Issue by arnauddorgans** [RxSwiftCommunity/RxSwiftExt#119]
I don't really understand the utility of the shouldRepeat predicate without the last element of the observable, how can I tel shouldRepeat = false if the last element of my Observable<Bool> is **false** for exemple ?

**expectation :**
`observable.repeatWithBehavior(.delayed(maxCount: UInt.max, time: 1), shouldRepeat: { $0 })`

`

    extension ObservableType {

    func repeatWithBehavior(_ behavior: RepeatBehavior, scheduler: SchedulerType = MainScheduler.instance, shouldRepeat: @escaping ((E?)->Bool)) -> Observable<Self.E> {
        return Observable<E>.create { observer in
            var lastElement: E?
            return self.repeatWithBehavior(behavior, scheduler: scheduler, shouldRepeat: {
                shouldRepeat(lastElement)
            }).subscribe { event in
                switch event {
                case .next(let element):
                    lastElement = element
                default:
                    break
                }
                observer.on(event)
            }
        }
    }
    }
`

**Comment by fpillet** [comment]
Not sure I understand this question. The predicate helps determine whether the sequence should or shouldn't repeat. To help it make its decision, the closure receives the last element (if any) that was emitted by the sequence. You may not use it at all in the decision process: it all depends on your context.

It really is up to you, the framework is just trying to help.

**Comment by Arnoymous** [comment]
@fpillet  yes but in the library there is no arguments in the closure :/ it's only a void 
`public typealias RepeatPredicate = () -> Bool`

`public func repeatWithBehavior(_ behavior: RepeatBehavior, scheduler : SchedulerType = MainScheduler.instance, shouldRepeat : RepeatPredicate? = nil) -> Observable<E>`

**Comment by Arnoymous** [comment]
that is why I would like to change the closure and add the last element if any, because just by calling the RepeatPredicate without any context is not really helpfull

**Comment by fpillet** [comment]
Ah ok sorry I didn't check back the operator source code first. So in essence, you _want_ to get the last item, whereas we are not currently providing it.

What if you needed the last two items to make a decision? Or the whole sequence?

I guess that we could add a second signature for `repeatWithBehavior` that pass an optional last element, I don't want to change the original signature.

**Comment by Arnoymous** [comment]
hmm yea I like that ! 👍

**Comment by freak4pc** [comment]
Hey @arnauddorgans  - I'm closing this for now due to inactivity - If you have any more comments on this subject, feel free to comment or ping me directly and I'll re-open it :) Thanks !
