### ISSUE TITLE
UIScrollView `reachedBottom`

### ISSUE THREAD

**Issue by mosamer** [RxSwiftCommunity/RxSwiftExt#122]
### Name and description
`UIScrollView` reactive extension for reaching bottom while scrolling.

### Motivation for inclusion
While `UIScrollView` already contains reactive extensions for `contentOffset` and scrolling to top, there is no such extension for reaching bottom of the scrollable content. This is commonly used to trigger pagination requests.

### Example of use
```
scrollView.rx
   .reachedBottom(edgeOffset: 10.0)
   .bind(to: viewModel.loadNextPage)
   .disposed(by: bag)
```

**Comment by freak4pc** [comment]
I agree this would be a great addition. 
Here's a simple implementation from Kruno on RxFeedback that we might want to use: 

https://github.com/NoTests/RxFeedback.swift/blob/master/Examples/GithubPaginatedSearch.swift#L192

I would just consider two things here:
1. the naming.  
2. does RxSwiftExt even have any support for "UI"-level extensions at this point?

**Comment by freak4pc** [comment]
Hey @mosamer - This is in my to-do list to add in RxSwiftExt fairly soon. Closing this for now :)

**Comment by freak4pc** [comment]
@mosamer Are you still interested in going after this implementation? :)

**Comment by mosamer** [comment]
@freak4pc I already had an implementation when posted this first time, let me find it and create a PR, hopefully, this weekend.

**Comment by jdisho** [comment]
Hey guys, what do you think about this implementation? 
I can take over if @mosamer is okay with it 😊 

```swift 
extension Reactive where Base: UIScrollView {
    func reachedBottom(offset: Double = 0.0) -> ControlEvent<Bool> {
        let observable = contentOffset
            .flatMap { [weak base] contentOffset -> Observable<Bool> in
                guard let scrollView = base else { return .empty() }
                let visibleHeight = scrollView.frame.height
                    - scrollView.contentInset.top
                    - scrollView.contentInset.bottom
                let y = contentOffset.y + scrollView.contentInset.top
                let threshold = max(offset, scrollView.contentSize.height - visibleHeight)

                return .just(y > threshold)
        }

        return ControlEvent(events: observable)
    }
}
```

**Comment by fpillet** [comment]
@jdisho why go for `flatMap` where a simple `map` would have done the job ? If the `guard` statement fails, just return false. Since you're not doing anything special on this error, I don't think using the more expensive `flatMap` is worth it.

Other than this, 👍

**Comment by fpillet** [comment]
Oh and also, you want to add a `distinctUntilChange` to remove duplicate states

**Comment by jdisho** [comment]
There is no problem with Krunoslav implementation @freak4pc. I just did my own and shared it. 😊
