### ISSUE TITLE
huge resource count leak on repeatWithBehavior and retryWithBehavior

### ISSUE THREAD

**Issue by arnauddorgans** [RxSwiftCommunity/RxSwiftExt#125]
I have found a huge leak on resource count when using repeatWithBehavior/retryWithBehavior
you can find out with a timer and **RxSwift.Resources.total**

### How to

1. use *TRACE_RESOURCES* on RxSwift
2. add this on your AppDelegate:
```swift
class AppDelegate: UIResponder, UIApplicationDelegate {
    func startDebugRxResources() {
        #if DEBUG
            _ = Observable<Int>.interval(1, scheduler: MainScheduler.instance)
                .subscribe(onNext: { _ in
                    print("Resource count \(RxSwift.Resources.total)")
                })
        #endif
    }
}
```
3. call it on didFinishLaunchingWithOptions
```swift
startDebugRxResources()
```
4. on a viewcontroller or everywhere:
```swift
Observable.just(1)
            .repeatWithBehavior(.immediate(maxCount: .max))
            .debug()
            .subscribe()
            .disposed(by: disposeBag)
```

5. just look at your logs

In like 15seconds i had this result:
```swift
Resource count 33
Resource count 48
Resource count 63
Resource count 78
Resource count 93
Resource count 108
Resource count 123
Resource count 138
Resource count 153
Resource count 168
Resource count 183
Resource count 198
Resource count 213
Resource count 228
Resource count 243
```

**Comment by freak4pc** [comment]
Your test is wrong - You're using an Observable in your AppDelegate that makes its own resources every second, so of course the count goes up uncontrollably. 

Remove the code from AppDelegate, instead put a print right before and a print `onDisposed` and then see what you get.

**Comment by Arnoymous** [comment]
@freak4pc nop, i have make a pull request and with it there is no more leak

**Comment by Arnoymous** [comment]
@freak4pc a simple test to find there is a bug:

juste add this on a viewcontroller or everywhere:

```swift
Observable.just(1)
            .repeatWithBehavior(.immediate(maxCount: .max))
            .debug()
            .subscribe()
            .disposed(by: disposeBag)
```

just wait like 20seconds and **boom** app crash

**Comment by freak4pc** [comment]
Let's continue discussion on this in your PR if it's still relevant #126
