### ISSUE TITLE
add average() operator

### ISSUE THREAD

**Issue by vincent-pradeilles** [RxSwiftCommunity/RxSwiftExt#145]
### Name and description

Include an operator that returns the running average for a sequence of `Numeric` values.

### Motivation for inclusion

Computing a running average can be tricky ([https://en.wikipedia.org/wiki/Moving_average#Cumulative_moving_average](https://en.wikipedia.org/wiki/Moving_average#Cumulative_moving_average)), so having it nicely encapsulated in a ready-to-use operator can be a nice feature.

Moreover, the fact that it's possible to compute a running average in an efficient way (O(1) for each increment) using the formula in the link above might not be a well-known fact.

**Comment by freak4pc** [comment]
There's an ongoing discussion in #34 actually, would love to get your opinions there @vincent-pradeilles !

**Comment by vincent-pradeilles** [comment]
Yes, @fpillet told me about a little bit earlier. So I'm going to close this issue, as it's a duplicate of the other one.

**Comment by freak4pc** [comment]
PS I don't think cumulative average is that hard 

`sum(stream) / count(stream)` usually

**Comment by freak4pc** [comment]
Sounds good - Let's discuss there @vincent-pradeilles

**Comment by vincent-pradeilles** [comment]
@freak4pc if you compute it this way, then your computation will O(n), for every `.next` event, which can be problematic for large sequences.

**Comment by freak4pc** [comment]
That's not necessarily true, you just need to accumulate the sum with the count of emissions as you go, which should be a O(1) IIRC.
