### ISSUE TITLE
UIViewPropertyAnimator extension

### ISSUE THREAD

**Issue by twittemb** [RxSwiftCommunity/RxSwiftExt#148]
Hi

### Name and description: UIViewPropertyAnimator extension
The purpose of this extension is to wrap a UIViewPropertyAnimator into a Completable to be able to chain animations very easily and in a RxSwift way: see https://medium.com/@thibault.wittemberg/elegantly-chaining-uiviewpropertyanimators-88409c64f845

### Motivation for inclusion: 
I can't find UIViewPropertyAnimator extension anywhere, so I wonder if RxSwiftExt is the best target for this kind of feature ? @freak4pc seems to think so on the Slack channel. I need a confirmation here, and I'd like to know in which folder I should put my files, since it is not a new Rx operator but rather a Rx extension. 

### Example of use: 
```swift
        self.animator1.rx.animate
            .andThen(self.animator2.rx.animate)
            .andThen(self.animator3.rx.animate)
            .andThen(self.animator4.rx.animate)
            .subscribe()
            .disposed(by: self.disposeBag)
```

**Comment by twittemb** [comment]
Does someone have an opinion on that ? perhaps RxSwiftExt is not the appropriate repo for that kind of extension ... I have no problem with that, I just wanted to know if there is a good repo for this kind of feature 😀 (or perhaps this feature is to basic to be considered as a good add-on ... I'm ready to hear that too👌)

thanks for your help.

**Comment by freak4pc** [comment]
Hey :) As discussed on slack I think this is a great addition. 
Additions to this repo take time unfortunately as It's mainly me for the past few weeks - other members are sometimes busier so review times may vary :) 

I think this would fit very well here and I would also like adding the operators potentially :)

**Comment by freak4pc** [comment]
Regarding location it would probably be a `UIViewPropertyAnimator+Rx.swift` file in RxCocoa much like this one: https://github.com/RxSwiftCommunity/RxSwiftExt/blob/master/Source/RxSwift/ObservableType%2BWeak.swift

**Comment by twittemb** [comment]
Hi @freak4pc 

Thanks for your response. Good to hear from you 👍

I will do a PR ASAP with these recommendations. 

I know how challenging can be an OpenSource project ... RxFlow takes me a LOT of time ! hard to be everywhere 😀

Thanks.

**Comment by freak4pc** [comment]
P.S We might want to make a `Components` folder inside. There was some discussion over here but not enough opinions. You can just put it in the RxCocoa folder ATM: 

https://github.com/RxSwiftCommunity/RxSwiftExt/issues/130

**Comment by twittemb** [comment]
Hi

The PR is here: https://github.com/RxSwiftCommunity/RxSwiftExt/pull/151

Thanks guys.

**Comment by twittemb** [comment]
I close this issue because a PR has been made ... this is always nice to have less issues in a repo 😀👍
