### ISSUE TITLE
unwarp(to:) Operator

### ISSUE THREAD

**Issue by iStefo** [RxSwiftCommunity/RxSwiftExt#152]
### Name and description
I propose the inclusion of an `unwrap(to:)` operator which maps `nil` values to the provided "default" value.

### Motivation for inclusion
This operator is handy when using KVO with RxSwift, as it always produces an observable of optional values.
Although it is pretty trivial to implement, the operator provides better readability than just using `map` directly because its use has a clearer intention.

By naming it `unwrap(to:)`, it feels both similar to `map(to:)` and `unwrap()`, and should therefore be easily discoverable.

### Example of use
```swift
extension ObservableType {
    public func unwrap<T>(to defaultValue: T) -> Observable<T> where E == T? {
        return self.map { $0 ?? defaultValue }
    }
}

// `observe` and `observeWeakly` will create an Observable<Bool?>
self.rx.observeWeakly(Bool.self, #keyPath(rowView.isSelected))
    .unwrap(to: false)
    .bind(to: self.button.rx.isEnabled)
```

If you think that this should be included I would happily create a PR including the implementation and tests.

**Comment by freak4pc** [comment]
`.map { $0 ?? false }` is just two characters longer then using `unwrap(to: false)` and is also more explicit IMO. 

I understand your specific motivation but, for me - specifically, this operator doesn't provide enough added value to be part of the library. This is just my personal opinion and of course doesn't prevent adding this operator :)  

If we do decide to implement it (e.g. if other people from @RxSwiftCommunity/contributors vote this up), we'll need to discuss the naming (e.g. `unwrap(or: T)` seems more appropriate, but maybe there are other options)

Thanks again for the discussion :)
Shai.

**Comment by jdisho** [comment]
I agree with @freak4pc in this argument, ` .map { $0 ?? ... } ` is more explicit and I don't see any problem writing it often. 🤔 
IMO, wrapping an "one line" operator with another one will make the code more confusing.

**Comment by jegnux** [comment]
@iStefo you should take a look at https://github.com/RxSwiftCommunity/RxOptional
It already includes a similar operator named `replaceNilWith(_:)`.

**Comment by iStefo** [comment]
@jegnux thanks, good tip
