### ISSUE TITLE
bufferUntil operator

### ISSUE THREAD

**Issue by sgtsquiggs** [RxSwiftCommunity/RxSwiftExt#158]
### Name and description

`bufferUntil` extension on `ObservableType`. Works like `skipUntil`, except buffering events instead of ignoring.

### Motivation for inclusion

For situations where you have a live stream that you must observe, but need to delay acting upon until an outside event occurs.

### Example of use

```swift
self.pickerView.rx.itemSelected
    .bufferUntil(self.textField.rx.controlEvent([.editingDidBegin]))
    .withUnretained(self)
    .map { arg -> String? in let (_self, (row: row, component: component)) = arg
        return _self.title(for: row, in: component)
    }
    .bind(to: self.textField.rx.text)
    .disposed(by: self.disposeBag)
```

### Rough implementation

```swift
extension ObservableType {
    public func bufferUntil<O: ObservableType>(_ other: O, limit: Int = 1) -> Observable<E> {
        let trigger = other.mapTo(true).startWith(false).take(2)
        return self.pausableBuffered(trigger, limit: limit)
    }
}
```

**Comment by freak4pc** [comment]
Seems a bit of a niche use-case which I'm not sure is 100% fitting for this repo. 
If I could get some more people's interest in this operator, It'd would be helpful to get a grasp for how needed it is. 

I'm also a bit bothered by the fact it uses 2 other RxSwiftExt operators (mapTo and pausableBuffered), as usually operators don't use other operators inside the repo. This isn't necessarily a huge issue but just noticed this might be a problem of sorts. 

In your example, wouldn't you get possibly unlimited number of emissions from the pickerView if many the selection was changed multiple times? It seems to me you would only want the latest of the bunch.

**Comment by sgtsquiggs** [comment]
1. I agree it may be a very limited use case. I found it very useful for myself and wanted to share in case it became more useful for others.

2. Sure! pausableBuffered is overkill for this use and mapTo is easily replaced.

3. My example use case is a UIPickerView in place of the keyboard. I have a UITextField that is observing the UIPickerView's value, but I do not want the UITextField to observe the UIPickerView's value until the UITextField has become active and the UIPickerView has become visible. This goes back to your point 1; this only has a very specific use case for me.

**Comment by freak4pc** [comment]
@sgtsquiggs Yeah in my view this is a bit too niche of a use-case to be a community-used operator. If you think otherwise I love to keep this open for more feedback but even you said its a bit too specific. Let me know your thoughts! :)
