### ISSUE TITLE
3.3.0 version is not available

### ISSUE THREAD

**Issue by tigran-stdev** [RxSwiftCommunity/RxSwiftExt#160]
New 3.3.0 release version is not available in Cocoapods.

<img width="371" alt="screen shot 2018-06-25 at 19 34 02" src="https://user-images.githubusercontent.com/36221236/41860103-cecf5686-78ae-11e8-960e-49afd258c940.png">
<img width="91" alt="screen shot 2018-06-25 at 19 33 50" src="https://user-images.githubusercontent.com/36221236/41860113-d342a36c-78ae-11e8-97a5-8bdf0d57227e.png">

**Comment by bobgodwinx** [comment]
@freak4pc @fpillet can slice a version for `CocoaPods 3.3.0`

**Comment by freak4pc** [comment]
Hey, thanks - you just need to push a new pod spec to trunk. The release is already out.

**Comment by freak4pc** [comment]
3.3.0 was pushed. Thanks for reporting :)
