### ISSUE TITLE
Add operator to add side effect to `catchErrorJustComplete`

### ISSUE THREAD

**Issue by vincent-pradeilles** [RxSwiftCommunity/RxSwiftExt#165]
### Name and description
Add the possibility to register a function to perform side-effects when an error occurs

### Motivation for inclusion
This can be helpful if we want to have a default value when an error occurs, whilst still login the error. (For instance, if the observable represents a web service call, we could send a hit to crashlytics)

### Example of use
```swift
import RxSwift

public extension Observable {
    public func catchErrorJustReturn(_ defaultValue: Element, onError: ((Error) -> Void)?) -> Observable<Element> {
        return self
            .do(onError: onError)
            .catchErrorJustReturn(defaultValue)
    }
}
```

```swift
import RxSwift
import RxSwiftExt

enum MyError: Error {
    case someError
}

example("catchError") {
    _ = Observable<Int>.create { obs in
        obs.onNext(1)
        obs.onNext(2)
        obs.onError(MyError.someError)

        return Disposables.create()
        }
        .catchErrorJustReturn(0, onError: { error in print(error) })
        .subscribe { event in
            print(event)
    }
}
```

This prints:

```
--- catchError example ---
next(1)
next(2)
someError
next(0)
completed
```

**Comment by freak4pc** [comment]
Uhm I don't think this really adds the much value - I actually think its much cleaner (and clearer to read) when they are chained after each other. You still have to pass in the default value and the error block, and the amount of code you would write is about the same (besides the `do`).

```
catchErrorJustReturn(_, onError:)
```

vs.

```
.**do**(onError:)
.catchErrorJustReturn(_)
```

In short, I don't think this provides enough benefit to add an overload for `catchErrorJustReturn`.

**Comment by vincent-pradeilles** [comment]
Yeah, that makes sense.

In my app I used it to build on top a function to send the `Error` to crashlytics, which has a lot of added-value; but without this additional process, there's indeed nothing much more than the standard operators.
