### ISSUE TITLE
Support `.not` for `Driver` and `Signal`

### ISSUE THREAD

**Issue by ericmarkmartin** [RxSwiftCommunity/RxSwiftExt#174]
### Name and description
We should add support for the `.not` operator to `Driver` and `Signal`

### Motivation for inclusion
The same as #161, except for `not` instead of `unwrap`

### Example of use
```swift
func configureLoadingState(_ isLoading: Driver<Bool>) {
    isLoading
        .not()
        .drive(self.loadingIndicator.rx.isHidden)
        .disposed(by: self.disposeBag)
}
```

**Comment by ericmarkmartin** [comment]
If someone gives me the green light, I'm happy to whip up a PR

**Comment by freak4pc** [comment]
Hey @ericmarkmartin, yup! that sounds good :) Thanks for taking initiative.

**Comment by ericmarkmartin** [comment]
I thought it was funny that this didn't exist by the extension provided in `not+RxCocoa`, but it appears that nothing in the `Source/RxCocoa` folder makes it into the pod. If that is fixed this issue should be fixed as well.

**Comment by ericmarkmartin** [comment]
I was able to get these files by adding `RxSwiftExt/RxCocoa` to my podfile—so I will close this issue, but the README should probably change to reflect that this is necessary to get some of the features.
