### ISSUE TITLE
Extension for withUnretained where Element == Void

### ISSUE THREAD

**Issue by yoavschwartz** [RxSwiftCommunity/RxSwiftExt#178]
### Name and description
I suggest adding an overload for `withUnretained` where the element type of the `Observable` is `Void` where the `Void` value will not be "forwarded" as its useless.
### Motivation for inclusion
I really enjoy the new operator, however, I believe at least 80% of the uses are to inject a safe strong reference of `self` to the subscribe block. When the `Observable` is of `Observable<Void>` which is very common in UI events, for example a `button.rx.tap`, we want to inject self to the `subscribe` but we really don't need the value. However, because the `Void` is sent along instead we have to explicitly use 
```
observableOfVoid.withUnretained(self).subscribe(onNext: { (strongSelf, _) in ... }
```
Instead I suggest making an overload that ignores void thus it would become
```
observableOfVoid..withUnretained(self).subscribe(onNext: { strongSelf in ... }
```
### Example of use

```
button.rx.tap.withUnretained(self)
.subscribe(onNext: { strongSelf in strongSelf.showButtonPressedAlert() }
```

### Implementation
I already have an implementation ready since I use it in my code, however since this is not a bug fix, seems like a discussion is due if this is important enough to be included.
```
extension ObservableType where E == Void {
    /**
     Provides an unretained, safe to use (i.e. not implicitly unwrapped), reference to an object replacing the element emitted by the sequence in case its `Void`.
     In the case the provided object cannot be retained successfully, the seqeunce will complete.
     
     - parameter obj: The object to provide an unretained reference on.
     - parameter resultSelector: A function to transform the unretained referenced on `obj`.
     - returns: An observable sequence that contains the result of `resultSelector` being called with an unretained reference on `obj`.
     */
    public func withUnretained<T: AnyObject, Out>(_ obj: T,
                                                  resultSelector: @escaping (T) -> Out) -> Observable<Out> {
        let fun: (T, Self.E) -> Out = { (element, _) in resultSelector(element) }
        return withUnretained(obj, resultSelector: fun)
    }
    
    /**
     Provides an unretained, safe to use (i.e. not implicitly unwrapped), reference to an object replacing the element emitted by the sequence in case its `Void`.
     In the case the provided object cannot be retained successfully, the seqeunce will complete.
     
     - parameter obj: The object to provide an unretained reference on.
     - returns: An observable sequence that contains an unretained reference on `obj`.
     */
    public func withUnretained<T: AnyObject>(_ obj: T) -> Observable<(T)> {
        return withUnretained(obj) { $0 }
    }
}
```

**Comment by MortyMerr** [comment]
Hey @yoavschwartz thank you for the detailed explanation of your point. I think that sounds reasonable and we can add this. 
@freak4pc what's your opinion?
