### ISSUE TITLE
I have updated Xcode10, and get some building error like following typing.

### ISSUE THREAD

**Issue by LieonShelly** [RxSwiftCommunity/RxSwiftExt#180]
I have updated xcode10, and get some building error like following typing:

public enum FilterMap<Result> {
    case ignore
    case map(Result) // Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'map(_:)' (identifier_name)

    fileprivate var asOperator: AnyOperator<Result> {
        switch self {
        case .ignore: return .filter
        case .map(let value): return .map(value)
        }
    }
}

**Comment by freak4pc** [comment]
Hey @LieonShelly - Can't reproduce this locally. Are you on the latest SwiftLint? Might be a bug.

**Comment by LieonShelly** [comment]
> Hey @LieonShelly - Can't reproduce this locally. Are you on the latest SwiftLint? Might be a bug.

yep, it's my older version swiftlint fucked up, Thanks
