### ISSUE TITLE
Carthage build fail in Xcode 10

### ISSUE THREAD

**Issue by krishnagniyes** [RxSwiftCommunity/RxSwiftExt#182]
/usr/bin/xcrun xcodebuild -workspace /Users/krishna_kumar/Documents/Mine/Projects/DSP/MemberApp/ios-dsp/Carthage/Checkouts/RxSwiftExt/RxSwiftExt.xcworkspace -scheme RxSwiftExt-iOS -configuration Release -derivedDataPath /Users/krishna_kumar/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/RxSwiftExt/3.3.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2r/nydxx3td24zffjbjtmkk3s8hb2qsqq/T/RxSwiftExt SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/krishna_kumar/Documents/Mine/Projects/DSP/MemberApp/ios-dsp/Carthage/Checkouts/RxSwiftExt)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2r/nydxx3td24zffjbjtmkk3s8hb2qsqq/T/carthage-xcodebuild.kcXmxm.log

**Comment by freak4pc** [comment]
Won't have much time to look into this over the next few days. 
Feel free to put up a PR and I can review it.

**Comment by krishnagniyes** [comment]
I've fixed this issue, 
Solution: Updated Carthage version & updated swifLint.
