### ISSUE TITLE
FlatMapZip

### ISSUE THREAD

**Issue by twittemb** [RxSwiftCommunity/RxSwiftExt#183]
### Name and description
Operator: FlatMapZip
Description: the existing "Zip" operators take the Observables to Zip and a closure to compute the data type to return. That return value will be wrapped into an Observable that we can subscribe to.

It is not possible to return directly an Observable in the closure that would be flatten by the Zip operator into the final Observable that we want to subscribe to.

FlatMapZip would take the Observables to Zip and a closure that returns an Observable.

### Motivation for inclusion
See the description.

### Example of use
```swift
Observable<String>.flatMapZip (observable1, observable2) { (value1, value2) -> Observable<String> in
    return api.fetchData(with: value1, and: value2)
}
```
Where 'api.fetchData()' returns an ```Observable<String>```

**Comment by freak4pc** [comment]
Hey @twittemb, always great seeing your new proposals :) 

Just to be clear, so this would be an alias for:

```swift
Observable.zip(piece1, piece2)
 .flatMapLatest { api.fetchData(with: piece1, and: piece2) }
```
?

**Comment by twittemb** [comment]
Hi @freak4pc 

In fact I didn't notice the notation you're suggesting. Xcode does not propose me this "zip" syntax with autocomplete, there is always a resultSelector closure :-(

My proposal makes no sense in that case. Thanks for letting me know this way of writing this 👍.

I close this issue.

See ya.
