### ISSUE TITLE
takeUntil(_: Completable)

### ISSUE THREAD

**Issue by Voxar** [RxSwiftCommunity/RxSwiftExt#187]
Hello. I have a suggestion for added overloads to the `takeUntil` operator

```swift
/// take until completable completes or errors out
takeUntil(_: Completable)
/// Like RxSwift.takeUntil(_: Observable) but until other completes.
/// Convenience for `takeUntil(other.ignoreElements())`
takeUntil(completed: Observable)
```

Example usage
```swift
let connection = network.connect(to: host).share()
let heartbeat = connection.flatMapLatest {
    Observable<Int>.interval(10.0, MainScheduler.instance)
	.takeUntil(completed: connection)}
        .withLatestFrom(connection)
	.flatMapLatest(sendHeartbeat)
	.subscribe()
    }
```

Possible implementation at https://github.com/RxSwiftCommunity/RxSwiftExt/compare/master...Voxar:takeUntilCompleted?expand=1

**Comment by freak4pc** [comment]
I like it ! Will gladly take a PR even though I’d argue this can even be in
the main repo possibly :)

-- 
Shai Mishali

**Comment by MortyMerr** [comment]
Opened pr to main repo here - https://github.com/ReactiveX/RxSwift/pull/1971
@Voxar approved that I can proceed with his idea

**Comment by MortyMerr** [comment]
@freak4pc what do u think about it? Main won't accept it, should I open PR here? It there any sense in this operator? Overwise, should we close this one?

**Comment by freak4pc** [comment]
I wanted to use it to begin with but given the discussion that emerged, I think it would cause too much confusion. For a completion it fits more with concat than a takeUntil. Closing for now.
