### ISSUE TITLE
 'OSAtomicOr32OrigBarrier' was deprecated

### ISSUE THREAD

**Issue by xiao99xiao** [RxSwiftCommunity/RxSwiftExt#200]
### Name and description
I'm using RxSwiftExt in a watchOS target app, and this warning has been existing for ages:
```
once.swift:30:23: 'OSAtomicOr32OrigBarrier' was deprecated in watchOS 3.0: Use atomic_fetch_or() from <stdatomic.h> instead
```

### Motivation for inclusion
Having this warning resolved by replacing it with the new `atomic_fetch_or()` or something would be great since Xcode no longer target below watchOS 3.0.

**Comment by freak4pc** [comment]
Hey. This is related to the RxSwift version you use, and not RxSwiftExt itself.

Update to RxSwift 4.4.1 and you should be fine.

**Comment by xiao99xiao** [comment]
@freak4pc I'm using RxSwift 4.4.1 and it still exists. The warning is  located at here:
https://github.com/RxSwiftCommunity/RxSwiftExt/blob/2204a685f7761244f311161f6c35ea0406488e17/Source/RxSwift/once.swift#L30

**Comment by freak4pc** [comment]
Ah I see. Sorry about misunderstanding your question.
