### ISSUE TITLE
CustomOperator protocol & flatMapSync deprecation suggestion

### ISSUE THREAD

**Issue by MortyMerr** [RxSwiftCommunity/RxSwiftExt#212]
`CustomOperator` protocol and `flatMapSync`  was introduced in 2017. Since then It has been used only once in the project. In `filterMap` implementation. With all respect to Jeremie Girault work, this code seems to be not very useful.

As it was mentioned before here https://github.com/RxSwiftCommunity/RxSwiftExt/pull/207 every operator needs to be as atomic as possible, cause user want ability to just copy paste needed function without pulling the whole project. User can't do it with `.filterMap` because of it overcomplicated implementation. 

Both `CustomOperator` and `flatMapSync` are public, however, they are not added to README.md and there are no tests on `flatMapSync`. The only purpose of this code is to implement `filterMap`. However, it could be done with a simple composition of `map` and `filter` operators and I guess it won't be less performant, but much more clear.

My suggestion is to deprecate `CustomOperator`,  `AnyOperator` and `flatMapSync` and change `filterMap` implementation. Or if you found `flatMapSync` very useful I will add tests and documentation on it. I am ready to contribute.

Please share your thoughts on that :)

**Comment by freak4pc** [comment]
Hey Anton,
I agree with you - 

1. I don't see a value for using any of the abstractions such as `AnyOperator` etc. for `filterMap`.

2. That implementation could be highly simplified, as you mentioned:

```swift
public enum FilterMap<Result> {
    case ignore
    case map(Result)
}

extension ObservableType {
    /**
     Filters or Maps values from the source.
     - The returned Observable will error and complete with the source.
     - `next` values will be output according to the `transform` callback result:
     - returning `.ignore` will filter the value out of the returned Observable
     - returning `.map(newValue)` will propagate newValue through the returned Observable.
     */
    public func filterMap<Result>(_ transform: @escaping (Element) -> FilterMap<Result>) -> Observable<Result> {
        return flatMap { element -> Observable<Result> in
            let filterMap = transform(element)
            switch filterMap {
            case .ignore:
                return .never()
            case .map(let result):
                return .just(result)
            }
        }
    }
}

```

3. The main question is if `flatMapSync` is being used by community members. If not, I'd also opt for removing it. If it _is_ used, I'd opt for leaving as is but never using its implementation details (AnyOperator etc) outside of that file, so operators are kept atomic as possible. 

@RxSwiftCommunity/contributors - Thoughts on this? Did any of you ever use `flatMapSync` for anything?

**Comment by MortyMerr** [comment]
Hey @freak4pc thank you for your answer, glad to see understanding from your side :)
Could u please provide a deadline for this question? I mean, if this issue won't get any answers for a week (or for how long?) could I open PR on `flatMapSync` removing? 

>The main question is if flatMapSync is being used by community members

Don't think so, cause it based in `CustomOperator` abstraction

**Comment by freak4pc** [comment]
Let's wait for any comments until June 1st.

**Comment by jegnux** [comment]
Hey @freak4pc, shouldn't `case .ignore` return `.empty()` instead of `.never()` in your implementation suggestion? 🤔

**Comment by MortyMerr** [comment]
@jegnux yes :)
It was implemented with .empty()  here https://github.com/RxSwiftCommunity/RxSwiftExt/pull/214

**Comment by freak4pc** [comment]
Was just scribbling :) thanks for the note Jerome

**Comment by freak4pc** [comment]
PS have to say that using empty is a bit strange. When you filter something using filter() it doesn’t complete the stream, it just “holds is” (like a never). 

WDYT @jegnux ?

**Comment by jegnux** [comment]
@freak4pc yeah but it's in a `flatMap`. If you use `never()`, the resource (NeverProducer) will never be released until the outer subscription is disposed, will it?

**Comment by freak4pc** [comment]
Uhm right I guess if it's inside a flatMap it makes sense to have it as empty

**Comment by MortyMerr** [comment]
I created PR on removing `flatMapSync` as was discussed https://github.com/RxSwiftCommunity/RxSwiftExt/pull/214

**Comment by MortyMerr** [comment]
Closed by https://github.com/RxSwiftCommunity/RxSwiftExt/pull/216
