### ISSUE TITLE
repeatEvery operator

### ISSUE THREAD

**Issue by thanegill** [RxSwiftCommunity/RxSwiftExt#22]
### repeatEvery

Repeats an observable sequence each period.

``` swift
extension ObservableType {
    /**
     Returns an observable sequence that repeats at each period.

     - seealso: [timer operator on reactivex.io](http://reactivex.io/documentation/operators/timer.html)

     - parameter period: Period to produce subsequent values.
     - returns: An observable sequence that repeat at each period.
     */
    @warn_unused_result(message="http://git.io/rxs.uo")
    public func repeatEvery(period: RxTimeInterval, scheduler: SchedulerType)
        -> Observable<E> {
            return Observable<Int>.timer(0, period: period, scheduler: scheduler)
                .flatMapLatest { _ in
                    return self
            }
    }
}
```
### Motivation for inclusion

Cleaner more readable repetition/polling for an observable.
### Example of use

``` swift
Observable<NSDate>.just(timerEnd)
    .repeatEvery(1, scheduler: MainScheduler.instance)
    .map { $0.timeIntervalSinceNow }
    .map(remainingTime.stringFromTimeInterval)
    .bindTo(timerLabel.rx_text)
```

**Comment by fpillet** [comment]
Excellent idea! While we're at it, why not do:

```swift
public func repeatEvery(period: RxTimeInterval, iterations : Int = 0, scheduler: SchedulerType)
```

So that by default, it never stops (iterations = 0) and you can specify a maximum iteracount count. Of course this could also be taken care of with `take(1)` so the idea may be too much.

Also, instead of sending `self` as a next element, we could send something more useful like the current iteration count, or the current time, or a tuple with both!

What do you think?

**Comment by thanegill** [comment]
@fpillet Yes!!

What about this instead?

```swift
public func repeatEvery(period: RxTimeInterval, iterations: UInt? = nil, scheduler: SchedulerType)
```
Where nil represents non stopping repetition. With a `Uint` so the negative check is on the user and not in the operator.

As far as emitting a tuple we should have an operator that does that but my original thinking was this as a convince operator for readability of repetition; to make it read more like prose. "Every second do this thing" vs. "Do this thing every second". Both are correct English but the latter might make more sense in case where "this thing" is more complicated than the repetition mechanism.

I also have an idea for an `repeatWhen` operator that will repeat when other observable emits for cases where the interval isn't consistent. My RxSwift+Time.swift file for my current project is full of fun operators that I'd like to get on here at some point.

**Comment by fpillet** [comment]
Ok let's make this tiny syntactic change to the iterations parameter:

```swift
public func repeatEvery(period: RxTimeInterval, maxIterations: UInt? = nil, scheduler: SchedulerType)
```

And I'm fine with this. Not a big fan of using optionals for numerical values though, but it makes as much sense here as making it `maxIterations: UInt = 0` default value, I guess :)

**Comment by thanegill** [comment]
Maybe two operators? Instead of nil or 0 indicating infinite.

**Comment by fpillet** [comment]
The `repeat` operator has been implemented along with `retry` with behavior
