### ISSUE TITLE
Cannot install via swift package manager – tag missing

### ISSUE THREAD

**Issue by svyatogor** [RxSwiftCommunity/RxSwiftExt#233]
Package.swift only exists in master branch and not under any of the tags, so it cannot be resolved by swift package manager. Please create a new tag of master (5.0.1 I guess?)

**Comment by vzsg** [comment]
You can also specify the master branch in Package.swift as a workaround. But 👍, a tag would be great to have.

**Comment by RamblinWreck77** [comment]
+1, just tried this with the Xcode 11 GM

**Comment by MortyMerr** [comment]
We are waiting for input from @freak4pc for new release )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freak4pc** [comment]
Will cut a release in a couple of hours. Thanks !
