### ISSUE TITLE
5.1.0's podspec.json missed watchOS platform

### ISSUE THREAD

**Issue by xiao99xiao** [RxSwiftCommunity/RxSwiftExt#237]
In the podspec.json of 5.1.0 here https://github.com/CocoaPods/Specs/blob/eddd738d79f28d9be449ec3864de6c1e2dbe7d04/Specs/b/0/1/RxSwiftExt/5.1.0/RxSwiftExt.podspec.json#L14 , the platform apparently missed `watchos` in the list, which exists in 5.0.0.

All projects containing a `Watch Extension` that uses RxSwiftExt will fail on `pod update RxSwiftExt`, with the error message below:
```
[!] The platform of the target `XXX Watch Extension` (watchOS 4.0) is not compatible with `RxSwiftExt (5.1.0)`, which does not support `watchos`.
```

This issue is probably caused by a wrong podspec pushed to Cocoapods master repo. Since it's affecting all watchos targets, I hope someone could get it fixed soon.
@freak4pc

**Comment by freak4pc** [comment]
Hey, this should be resolved now in 5.1.1. Thanks for pinging me!
