### ISSUE TITLE
Support RxSwift 5.1.0

### ISSUE THREAD

**Issue by 0xhiroki** [RxSwiftCommunity/RxSwiftExt#247]
Hi everyone,

There's a new version (5.1.0) in RxSwift which includes a fix for [Apple's hard deprecation, starting April 2020.](https://developer.apple.com/news/?id=12232019b). Please update the RxSwift dependency version to 5.1.0.

**Comment by jdisho** [comment]
I think this should work out of the box without any further changes. In this lib RxSwift is set to `~> 5.0`, which includes 5.1 too. 

Can you try by doing a `pod update`?

**Comment by 0xhiroki** [comment]
You are right! I will close this.
