### ISSUE TITLE
RxSwift 6

### ISSUE THREAD

**Issue by jlrrsands** [RxSwiftCommunity/RxSwiftExt#255]
Hi, we're hoping to upgrade to RxSwift 6 in our project as we also upgrade to XCode 12, is there any plans to update the RxSwiftExt dependency from 5 to 6 too?

**Comment by freak4pc** [comment]
Definitely on my to-do list with RxSwift 6 final coming out soon. I'll try getting to it or at least put up a branch/PR soon. Thanks !

**Comment by freak4pc** [comment]
Please try the `rxswiftext6` branch and let me know if you find anything funky. Thanks!

**Comment by jdisho** [comment]
Closing this issue because of #259.
