### ISSUE TITLE
6.0.0 .xcframework generation exception via Carthage

### ISSUE THREAD

**Issue by DmitriyBagrov92** [RxSwiftCommunity/RxSwiftExt#261]
### Carthage 0.36.1, Xcode 12.4, RxSwiftExt 6.0.0 can't be attached as dependency with exception:
*** Checking out RxSwift at "6.0.0"
*** Checking out XCGLogger at "7.0.1"
*** Checking out RxSwiftExt at "6.0.0"
*** Checking out YapDatabase at "4.0.1"
*** xcodebuild output can be found in /var/folders/h9/m2y6wd75175c2hlxmx7tnrc40000gn/T/carthage-xcodebuild.9qTXG7.log
*** Downloading RxSwift.framework binary at "Ethan"
*** Building scheme "RxBlocking" in Rx.xcworkspace
*** Building scheme "RxRelay" in Rx.xcworkspace
*** Building scheme "RxCocoa" in Rx.xcworkspace
*** Building scheme "RxSwift" in Rx.xcworkspace
*** Building scheme "RxTest" in Rx.xcworkspace
*** Building scheme "RxSwiftExt-tvOS" in RxSwiftExt.xcworkspace
*** Building scheme "RxSwiftExt-macOS" in RxSwiftExt.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/d.bagrov/apple-messaging-sdk/Carthage/Checkouts/RxSwiftExt/RxSwiftExt.xcworkspace -scheme RxSwiftExt-macOS -configuration Release -derivedDataPath /Users/d.bagrov/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/RxSwiftExt/6.0.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/h9/m2y6wd75175c2hlxmx7tnrc40000gn/T/RxSwiftExt SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/d.bagrov/apple-messaging-sdk/Carthage/Checkouts/RxSwiftExt)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/h9/m2y6wd75175c2hlxmx7tnrc40000gn/T/carthage-xcodebuild.9qTXG7.log

### Example of use
1. add to Carthfile file line: github "RxSwiftCommunity/RxSwiftExt" "6.0.0"
2. run carthage update --use-xcframeworks
3. Got and exception log: carthage-xcodebuild.9qTXG7.log

**Comment by DmitriyBagrov92** [comment]
[Uploading carthage-xcodebuild.9qTXG7.log…]()

**Comment by freak4pc** [comment]
Did you check just RxSwift without the other dependencies in an empty project? Please provide that project if so:) thank you!

**Comment by DmitriyBagrov92** [comment]
> Did you check just RxSwift without the other dependencies in an empty project? Please provide that project if so:) thank you!

Yes, RxSwift 6.0.0 is building without problems:
![Uploading image.png…]()

**Comment by DmitriyBagrov92** [comment]
I have an issue only because of RxSwiftExt attaching:
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/21103526/106159160-90a9ca80-6195-11eb-9f18-440656c5aff3.png">

**Comment by DmitriyBagrov92** [comment]
here the log: 
[carthage-xcodebuild.9qTXG7.log](https://github.com/RxSwiftCommunity/RxSwiftExt/files/5888261/carthage-xcodebuild.9qTXG7.log)

**Comment by freak4pc** [comment]
I don't believe we've added official XCFramework support but I'm happy to accept a PR if you're willing to debug it. Not sure I'll have time to do it myself in the coming weeks.

**Comment by DmitriyBagrov92** [comment]
> I don't believe we've added official XCFramework support but I'm happy to accept a PR if you're willing to debug it. Not sure I'll have time to do it myself in the coming weeks.

Ok, really appreciate for the quick answer. I'll try to fix it myself!

**Comment by freak4pc** [comment]
I think this should be fixed in 6.1.0. Thanks.
