### ISSUE TITLE
RxSwift 6.1 support

### ISSUE THREAD

**Issue by alex-vasenin** [RxSwiftCommunity/RxSwiftExt#263]
It would be nice if we could update to [6.1](https://github.com/ReactiveX/RxSwift/releases/tag/6.1.0)

**Comment by freak4pc** [comment]
Thanks for reporting Alex. This is just a mistake in the podspec, it should probably just be `~> 6.0` since there aren't actual code changes to worry about here.

Thanks for the report, I'll take care of it tomorrow.

**Comment by freak4pc** [comment]
Should be in 6.0.1
