### ISSUE TITLE
Carthage fails to resolve dependency on RxSwift (RxSwiftExt 6.0.1)

### ISSUE THREAD

**Issue by hello-im-szymon** [RxSwiftCommunity/RxSwiftExt#265]
### Name and description

It seems that RxSwiftExt in version 6.0.1 cannot properly resolve dependency on RxSwift. 
I've tried to add it in Cartfile using two different ways and there are two very different results. Please see examples below.
For testing purposes it's an empty folder with only Cartfile inside.

Carthage version: `0.37.0`

### Example of use

Cartfile: `github "RxSwiftCommunity/RxSwiftExt"  == 6.0.1`
Terminal:
```
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching RxSwiftExt
*** Fetching RxSwift
*** Checking out RxSwiftExt at "2.0-beta.1"
*** Checking out RxSwift at "2.6.1"
```

Cartfile: `github "RxSwiftCommunity/RxSwiftExt" "6.0.1"`
Terminal:
```
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching RxSwift
Failed to check out repository into /Users/mamczurs/Library/Caches/org.carthage.CarthageKit/dependencies/RxSwift: No object named "~> 6.0" exists (A shell task (/usr/bin/env git rev-parse ~>\ 6.0^{object} (launched in /Users/mamczurs/Library/Caches/org.carthage.CarthageKit/dependencies/RxSwift)) failed with exit code 128:
fatal: ambiguous argument '~> 6.0^{object}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
)
```

And here's an example using 6.0.0, everything is working as expected:
Cartfile: `github "RxSwiftCommunity/RxSwiftExt"  == 6.0.0`
Terminal:
```
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching RxSwiftExt
*** Checking out RxSwift at "6.0.0"
*** Checking out RxSwiftExt at "6.0.0"
*** xcodebuild output can be found in /var/folders/zb/qc3mvrcd1f9_3y71nnwd0s0xxfxhfl/T/carthage-xcodebuild.0fuRmu.log
*** Downloading RxSwift.framework binary at "Ethan"
```

**Comment by freak4pc** [comment]
Can you provide an example project with the issue? 
Thanks

**Comment by hello-im-szymon** [comment]
Calling it a project is a stretch, it only contains Cartfile with just RxSwiftExt in it

[RxSwiftExtCarthage601.zip](https://github.com/RxSwiftCommunity/RxSwiftExt/files/6410957/RxSwiftExtCarthage601.zip)

```
$ carthage version
0.37.0
```

**Comment by hello-im-szymon** [comment]
There are now 2 PRs addressing this issue:
https://github.com/RxSwiftCommunity/RxSwiftExt/pull/264
https://github.com/RxSwiftCommunity/RxSwiftExt/pull/266
