### ISSUE TITLE
Update podspec for 6.1.0

### ISSUE THREAD

**Issue by foxware00** [RxSwiftCommunity/RxSwiftExt#269]
Are we able to update the podspec to keep up-to-date with the latest release?

```
[!] CocoaPods could not find compatible versions for pod "RxSwiftExt":
  In Podfile:
    RxSwiftExt (~> 6.1.0)

```

**Comment by WestFlow127** [comment]
Same

**Comment by michalnowak061** [comment]
bump

**Comment by YoannLth** [comment]
Same for me regarding the latest update `6.2.0`

As a workaround you can target a specific commit in your podfile to get the latest version:
`pod 'RxSwiftExt', :git => 'https://github.com/RxSwiftCommunity/RxSwiftExt', :commit => 'a8065d1'`

**Comment by freak4pc** [comment]
See https://github.com/RxSwiftCommunity/RxSwiftExt/issues/273#issuecomment-1726826871
