### ISSUE TITLE
 Update podspec for 6.2.0 in cocoapods master repo

### ISSUE THREAD

**Issue by dk53** [RxSwiftCommunity/RxSwiftExt#273]
### Description

Following https://github.com/RxSwiftCommunity/RxSwiftExt/issues/269

Last version available on cocoapods master repo is 6.0.1 : https://github.com/CocoaPods/Specs/commit/bf02afbb90d6c8bf3712e705a403d6abb92e4169

### Motivation for inclusion

6.2.0 as been released [last week](https://github.com/RxSwiftCommunity/RxSwiftExt/blob/main/RxSwiftExt.podspec) but is unavailable though cocoapods update unless pointing directly to the commit like @YoannLth mentionned it [here](https://github.com/RxSwiftCommunity/RxSwiftExt/issues/269#issuecomment-1695342524) 

` pod 'RxSwiftExt', :git => 'https://github.com/RxSwiftCommunity/RxSwiftExt', :commit => 'a8065d1'`

### Solution

We should push this new version to cocoapods repo for users beeing able to update it with a classic `pod update RxSwiftExt`

**Comment by michalnowak061** [comment]
bump

**Comment by dk53** [comment]
cc @freak4pc

**Comment by michalnowak061** [comment]
The life of this library is coming to an end. It must be removed from the project 😕

**Comment by foxware00** [comment]
@freak4pc could you please help here, it's a shame to have to specify commit hashes in our podfiles

**Comment by michalnowak061** [comment]
additionally podspec files doesn't support specify commit hash :)

**Comment by freak4pc** [comment]
hey all,
sorry for the delay. to be honest the main reason I'm not updating the spec is because it's insanely difficult to use CocoaPods to upload specs. It's ridden with a lot of cryptic error messages. 

I had to spin up an entire CI machine just so I'll be able to push the spec, but seems to be working now.

Released 6.2.1.

**Comment by dk53** [comment]
It is ! 

Thank you very much sir!
