### ISSUE TITLE
Version 6.2.1 is not available on CocoaPods yet

### ISSUE THREAD

**Issue by khuong291** [RxSwiftCommunity/RxSwiftExt#277]
Can you help to upload version 6.2.1 to CocoaPods 🙏 . It's still showing 6.0.1 which is not working on XCode 15
<img width="506" alt="Screenshot 2023-09-28 at 15 40 57" src="https://github.com/RxSwiftCommunity/RxSwiftExt/assets/11523438/e418c481-4f3c-4fba-8898-a4cfc4d8f037">

**Comment by nuke-dash** [comment]
I use this in the podfile to work around it.
`pod 'RxSwiftExt', :git => 'https://github.com/RxSwiftCommunity/RxSwiftExt.git', :tag => '6.2.1'`

**Comment by khuong291** [comment]
> I use this in the podfile to work around it. `pod 'RxSwiftExt', :git => 'https://github.com/RxSwiftCommunity/RxSwiftExt.git', :tag => '6.2.1'`

Thanks, it works!
