### ISSUE TITLE
Privacy Manifest file update

### ISSUE THREAD

**Issue by Dreczek** [RxSwiftCommunity/RxSwiftExt#279]
### Privacy Manifest file update

I would like to know if there's a plan to create and release **privacy manifest** file 🙂?

### Motivation for inclusion

References on Apple's side:
https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/news/?id=av1nevon
https://developer.apple.com/app-store/user-privacy-and-data-use/

**Comment by mithleshgomotive** [comment]
+1 to above.

**Comment by freak4pc** [comment]
See discussion in https://github.com/ReactiveX/RxSwift/issues/2567

**Comment by rheekd** [comment]
They have decided as per the link
https://github.com/ReactiveX/RxSwift/issues/2567#issuecomment-2008689007
