### ISSUE TITLE
catchErrorJustComplete

### ISSUE THREAD

**Issue by sergdort** [RxSwiftCommunity/RxSwiftExt#29]
### Name and description

`catchErrorJustComplete ` completes sequence if it fails with error

### Motivation for inclusion

- improves declarative nature of Rx, so you don't need to write every time:

`catchError { return Observable.empty() }``

### Example of use

```swift
    someObservable.catchErrorJustComplete
```

I remember that it has been proposed in slack by dpaschich . So he probably the one who would like to port it :)

**Comment by thanegill** [comment]
Maybe I'm not undressing something, but doesn't the sequence complete after an uncaught error anyway?

**Comment by sergdort** [comment]
Yes, if think about it as no elements will be emitted

But you what do design API behavior, in therms of sequences that never fails this is what `catchErrorJustComplete` operator for

**Comment by fpillet** [comment]
Implemented by 0bf6365
