### ISSUE TITLE
repeatWhen

### ISSUE THREAD

**Issue by thanegill** [RxSwiftCommunity/RxSwiftExt#38]
### repeatWhen

Repeats an observable when another observable emits. 

``` swift
extension ObservableType {
    @warn_unused_result(message="http://git.io/rxs.uo")
    public func repeatWhen<O: ObservableConvertibleType>(@autoclosure notificationHandler: (() -> O)) -> Observable<E> {
        return notificationHandler()
            .asObservable()
            .flatMapLatest { _ in
                return self
            }
    }
}
```
### Motivation for inclusion

https://github.com/ReactiveX/RxSwift/issues/396
### Example of use

Polling where the repetition intervals are not equal. 

Could be one of the underlying operators for #15.

**Comment by fpillet** [comment]
Sounds like a reasonable proposition! Like it.

**Comment by dchohfi** [comment]
Is this going to be merged?

**Comment by fpillet** [comment]
Will gladly merge - we just need some tests to go with! Thanks for the heads up

**Comment by danlozano** [comment]
+1 for this feature.

Need it to do polling.

**Comment by freak4pc** [comment]
I'm closing this for now due to inactivity - If you have any more comments on this subject, feel free to comment or ping me directly and I'll re-open it :) Thanks !
