### ISSUE TITLE
Someone needs to be the point of contact for the CONDUCT.md

### ISSUE THREAD

**Issue by solidcell** [RxSwiftCommunity/RxSwiftExt#40]
In the recently added `CONDUCT.md`, no one replaced `[INSERT EMAIL ADDRESS]` with their email address.  I'm not sure who it would/should be, so I made this an issue instead of a pull request.

https://github.com/RxSwiftCommunity/RxSwiftExt/commit/e0f2c4a1050d431c036104d3acf7c3afde21bc25#diff-46b8dc461fb4104140b72e4043aaeefeR58

**Comment by fpillet** [comment]
Added my email address. Thanks for the heads up!
