### ISSUE TITLE
pausable operator

### ISSUE THREAD

**Issue by dpassage** [RxSwiftCommunity/RxSwiftExt#41]
### Name and description

`pausable` - pauses emission of values. 

### Motivation for inclusion

Provides a simple way to filter one observable based on the current state of another. Can be composed of `withLatest` and `filter`, but having a specific operator improves readability.

### Example of use

```swift
let thingThatNeedsTheSpeaker: Observable<Thing>.create { ... }
let noCallInProgress = Observable<Bool>.create { /* wrapper around CoreTelephony.CTCallCenter() */ }

let validThings = thingThatNeedsTheSpeaker.pausable(noCallInProgress)
```

**Comment by fpillet** [comment]
I like the idea

**Comment by kzaher** [comment]
Hi guys,

maybe it would make sense to make this compatible with https://github.com/Reactive-Extensions/RxJS/search?utf8=%E2%9C%93&q=Pausable.

**Comment by fpillet** [comment]
Seems to me this is the case (RxJS's `pausable` take a `pauser: Observable<boolean>`argument, which is equivalent to what's being proposed above). Did I misread it?

**Comment by kzaher** [comment]
@fpillet I am just aware that RxJS has pausable, haven't used it, but it seems it behaves like you say :)
