### ISSUE TITLE
pairwise, nwise operators

### ISSUE THREAD

**Issue by solidfox** [RxSwiftCommunity/RxSwiftExt#42]
### parwise(), nwise(n:)

Transforms a sequence to return every consecutive pair of emissions.
### Motivation for inclusion

One often need to compare a previous value for changes, this would make that simpler than the rather convoluted combination of .scan, .filter, .map needed to achieve this currently.
### Example of use

```
-----0-----1-----2-----3-----4----->
.parwise()
     v     v     v     v     v
---------(0,1)-(1,2)-(2,3)-(3,4)--->

```

**Comment by fpillet** [comment]
isn't it what `zip`is for?

**Comment by solidfox** [comment]
While you can achieve this by zipping a sequence with it's tail: `Observable.zip(sequence.skip(1), sequence)` this still seems too bothersome to me. Seeing as you have to interrupt your chaining to do this and it becomes rather convoluted when you start doing it for more than pairs.

This is how my pairwise looks:

```Swift
    @warn_unused_result(message="http://git.io/rxs.uo")
    public func pairwise() -> Observable<(E,E)> {
        var previous:E? = nil
        return self
            .filter { element in
                if previous == nil {
                    previous = element
                    return false
                } else {
                    return true
                }
            }
            .map { (element:E) -> (E,E) in
                defer { previous = element }
                return (previous!, element)
            }
        
    }
```

**Comment by fpillet** [comment]
Fun, I just realized I often need this

**Comment by freak4pc** [comment]
That's pretty neat :)

**Comment by vzsg** [comment]
I don't think this is less convoluted than a `scan`.

How about this?

```
extension ObservableType {
    public func nwise(_ n: Int) -> Observable<[E]> {
        return self
            .scan([]) { acc, item in Array((acc + [item]).suffix(n)) }
            .filter { $0.count == n }
    }

    public func pairwise() -> Observable<(E, E)> {
        return self.nwise(2)
            .map { ($0[0], $0[1]) }
    }

    public func ternate() -> Observable<(E, E, E)> {
        return self.nwise(3)
            .map { ($0[0], $0[1], $0[2]) }
    }
}
```

**Comment by fpillet** [comment]
@vzsg very nice implementation! I love the `nwise` implementation! Do you want to push a PR with tests, or should I go ahead and add it ?

**Comment by vzsg** [comment]
I'll try. 👍
