### ISSUE TITLE
Count operator

### ISSUE THREAD

**Issue by kciter** [RxSwiftCommunity/RxSwiftExt#43]
### Name and description

Count operator

Count the **number of items** emitted by the source Observable and emit only this value
### Motivation for inclusion

RxSwift doesn't have `count` operator now.
If you need the number of Observable, you can write the code as follows.

``` swift
[1, 2, 3, 4].toObservable()
    .reduce(0) { a, _ in
        return a + 1
    }
```

In addition, filtering is as below.

``` swift
[1, 2, 3, 4].toObservable()
    .filter { $0 <= 2 }
    .reduce(0) { a, _ in
        return a + 1
    }
```

I have difficulty in understanding what the code is about at a glance.
I think 'count' operator can solve this problem.

``` swift
[1, 2, 3, 4].toObservable()
    .count { $0 <= 2 }
```
### Example of use

``` swift
// Count.swift
import Foundation

class CountSink<SourceType, O: ObserverType where O.E == Int>: Sink<O>, ObserverType {
    typealias Predicate = (SourceType) throws -> Bool

    private let _predicate: Predicate?
    private var _count: Int = 0

    init(predicate: Predicate?, observer: O) {
        _predicate = predicate
        super.init(observer: observer)
    }

    func on(event: Event<SourceType>) {
        switch event {
        case .Next(let value):
            do {
                let satisfies = try _predicate?(value)
                if satisfies != false {
                    self._count += 1
                }
            }
            catch let e {
                forwardOn(.Error(e))
                dispose()
            }
        case .Error(let error):
            forwardOn(.Error(error))
        case .Completed:
            forwardOn(.Next(_count))
            forwardOn(.Completed)
            dispose()
        }
    }
}

class Count<SourceType>: Producer<Int> {
    typealias Predicate = (SourceType) throws -> Bool

    private let _source: Observable<SourceType>
    private let _predicate: Predicate?

    init(source: Observable<SourceType>, predicate: Predicate?) {
        _source = source
        _predicate = predicate
    }

    override func run<O: ObserverType where O.E == Int>(observer: O) -> Disposable {
        let sink = CountSink(predicate: _predicate, observer: observer)
        sink.disposable = _source.subscribe(sink)
        return sink
    }
}
```

``` swift
// Observable+Aggregate.swift
extension ObservableType {
    public func count(predicate: ((E) throws -> Bool)? = nil)
        -> Observable<Int> {
            return Count(source: self.asObservable(), predicate: predicate)
    }
}
```

``` swift
// Example.swift
[1, 2, 3, 4].toObservable()
    .count { $0 <= 2 }
    .subscribeNext { count in
        print(count) // output: 2
    }
```

**Comment by icanzilb** [comment]
Isn't this more of a thing that would go into RxSwfit @kzaher ? http://reactivex.io/documentation/operators/count.html

**Comment by kzaher** [comment]
Hi guys,

It would probably be best to not include this operator in the main repo for now unless we find some really compelling real world use cases :)

Reasons against adding rarely used convenience operators:
* increase compile time
* increase shipping size
* increase number of operators, so it's harder for beginners to find useful ones
* it's easily derivable from reduce operator (together with sum, avg, ....)
...

**Comment by sergdort** [comment]
Hm.. 
Am I missing something or this operator behaves kinda `filter` because there is `predicate` closure?
If, it is what would be a behavior in this case: `.count { $0 % 2 == 0 }` ?

**Comment by icanzilb** [comment]
@sergdort just look up the link I posted few comments above

**Comment by sergdort** [comment]
Haha :) my bad

**Comment by kciter** [comment]
@kzaher Okay. I understood :)

**Comment by freak4pc** [comment]
I'm closing this for now due to inactivity - If you have any more comments on this subject, feel free to comment or ping me directly and I'll re-open it :) Thanks ! 

P.S In general I kinda like this operator. Could be useful.

**Comment by polonez** [comment]
How about adding `count` operator to this repo(RxSwiftExt) instead of RxSwift?

**Comment by freak4pc** [comment]
I think there was very low demand for this but I'm not against reviewing a PR with this operato.

**Comment by WestFlow127** [comment]
This count operator doesn't recognize collections. So I obtained a solution from a fellow swift dev, Daniel, in the RxSwift Slack: 

```
extension ObservableType where Element: Sequence {
	func elementCount(_ isIncluded: @escaping (Element.Element) -> Bool) -> Observable<Int> {
		map { $0.filter(isIncluded).count }
	}
}
```

pop this in the project and you can count items with certain ID like so:

```
let foo = myObs  // where myObs is something like Observable<[ReplyEntity]>
    .elementCount { $0.id == comment.id }
```

Daniel noted the following: "Their count tracks a count of the number of next events that satisfy a predicate, where this count tracks the number of values in a sequence from each next event that satisfy the predicate."
So he named it `elementCount(_ isIncluded: @escaping (Element.Element) -> Bool) -> Observable<Int> `
