### ISSUE TITLE
limitRateOrDistinct

### ISSUE THREAD

**Issue by tcurdt** [RxSwiftCommunity/RxSwiftExt#44]
This is the result of a chat in the Slack channel.

I was looking for a way to turn

`4-4-4-------------4-4-----------4-5` into `4-4-4-5`

which is something in between `distinct` and `debounce`.

Here is the suggested solution (which is untested yet):

```
extension ObservableType where E: Equatable {
    public func limitRateOrDistinct(rate: Double, scheduler: SchedulerType) -> Observable<E>{
        var lastEmit: (item: E, time: NSDate)?
        return self.flatMap { (newItem: E) -> Observable<E> in
            guard let lastEmit = lastEmit else { return Observable.just(newItem) }
            return scheduler.now.timeIntervalSinceDate(lastEmit.time) > rate
                || lastEmit.item != newItem ? .just(newItem) : .empty()
            }
            .doOnNext { emitted in
                lastEmit = (emitted, scheduler.now)
            }
    }
}
```

**Comment by freak4pc** [comment]
I'm closing this for now due to inactivity - If you have any more comments on this subject, feel free to comment or ping me directly and I'll re-open it :) Thanks !
