### ISSUE TITLE
bindErrorTo

### ISSUE THREAD

**Issue by dangthaison91** [RxSwiftCommunity/RxSwiftExt#52]
### Name and description

`bindErrorTo` bind error from Observable to an `Observer<ErrorType>`.
This is my current implementation:

``` Swift
extension ObservableType {
    @warn_unused_result(message="http://git.io/rxs.uo")
    func bindErrorTo<O: ObserverType where O.E == ErrorType>(observer: O) -> Observable<E> {
        return doOnError { observer.onNext($0) }
    }
}
```
### Motivation for inclusion

When implement MVVM, especial with UIBinding (like RxDataSources), my ViewModel often has `error: PublishSubject<ErrorType>` to handle Error. So when i make some logics, request data from network... i need to inject side effects by calling `doOnError`:

``` Swift
class SomeViewModel {
    private let errorSubject: PublishSubject<ErrorType> = PublishSubject<ErrorType>()
    var errors: Observable<ErrorType> { return errorSubject.asObservable() }

// Request data
 didBecomeActive
            .flatMapLatest { [unowned self] _ in
                return self.getProfileDetail()
                    .doOnError { self.errorSubject.onNext($0) }
                    .catchErrorJustComplete()
            }
}
```
### Example of use

With convenient operator:

``` Swift
// Request data
 didBecomeActive
            .flatMapLatest { [unowned self] _ in
                return self.getProfileDetail()
                    .bindErrorTo(self.errorSubject)
                    .catchErrorJustComplete()
            }
}
```

**Comment by fpillet** [comment]
I can see how this could be a useful addition! I'm not sure about the operator name though, but don't have a better proposition at the moment. Let's go for it! Can you make a PR ?

**Comment by dangthaison91** [comment]
I'm sorry for not replying soon, have to run for deadline in this month. I think i need to upgrade to macOS Siera then setup RxSwift with Playground before making a PR for both Swift 2.2 & 3.0.

Hope i can do next week.

**Comment by fpillet** [comment]
No hurry. A recent PR I accepted broke the Swift3 project and now I have to start it all over

**Comment by mosamer** [comment]
I think the current naming is confusing with the existing RxCocoa method `bindTo` so I would suggest either;
- change the method name to reflect that it's doing a side-effect
- change the return type to `Disposable` in order to be a counterpart for RxCocoa implementation.

**Comment by fpillet** [comment]
Hi @mosamer,

Good idea, do you have a better idea for a name? I understand that `bindErrorTo` is too close to `bindTo`.

What about `doForwardErrors(to:)` ?

**Comment by mosamer** [comment]
may be drop _do_ as _forward_ is already a verb so it becomes `forwardErrors(to:)`?

**Comment by mosamer** [comment]
Also, here is a suggested implementation for `bindeErrorTo()`

```
extension ObservableType {
    func bindErrorTo<O: ObserverType>(_ observer: O) -> Disposable where O.E: Error {
        return self.subscribe(onError: {error in
            observer.onNext(error)
        })
    }
}
```

**Comment by dangthaison91** [comment]
1 vote for @fpillet idea but I think: `forwardErrors(to: )` is better.

@mosamer My first initial idea was using `bindeErrorTo` for better syntax when using `doOnError`, not intended for subscribeError. You can see in above examle.

**Comment by mosamer** [comment]
@dangthaison91 exactly! hence my suggestion to change the name :)

**Comment by dangthaison91** [comment]
Totally agree with `forwardErrorsTo(:)` for Swift 2.2 & `forwardErrors(to:)` for Swift 3.0

**Comment by dangthaison91** [comment]
Hey @fpillet really sorry for pending this so long. But now I think we should handle error in `flatMap` by using `materialize` operator. RxSwiftExt already have 2 extension `elements` and `errors` for materialize, that make handling is easier.  We should close this issue?

**Adam Borek** published a nice blog post about this: http://adamborek.com/how-to-handle-errors-in-rxswift/

**Comment by fpillet** [comment]
Closing issue as `materialize` should be used instead
