### ISSUE TITLE
The podspec references RxSwift 2.6

### ISSUE THREAD

**Issue by MadsBogeskov** [RxSwiftCommunity/RxSwiftExt#55]
The new podspec for release 1.2 requires RxSwift 2.6, but shouldn't it require 3.0.0-beta.1? Since 2.6 is Swift 2.3 support only.

**Comment by fpillet** [comment]
The dependency currently references "RxSwift 2.4 or later". RxSwiftExt 1.2 is still for Swift 2, while the `swift3` branch is for Swift 3.

**Comment by MadsBogeskov** [comment]
Arh okay! Thanks.
