### ISSUE TITLE
Distinct Requires Parameter

### ISSUE THREAD

**Issue by wassimseif** [RxSwiftCommunity/RxSwiftExt#57]
The `Distinct` operator requires a parameter of type `NSPredicate`. Can't use `distinct` just to check if string fails w match any of the previous events. This is different from the `distinct` operator in other libraries like `RxJava`

**Comment by fpillet** [comment]
There are several implementations of `distinct` that don't require a parameter: they work when the elements in the sequence are either `Hashable` or `Equatable`. Will work just fine with Strings.

Did you try them?

**Comment by wassimseif** [comment]
This is my code
``` 
searchTextField
    .rx.textInput.text
            .debounce(0.5 , scheduler: MainScheduler.instance)
            .distinct() // Missing argument for parameter #1 in call 
            .filter({ (string : String?) -> Bool in
                return (string?.characters.count)! > 2
            })
           
            
            .observeOn(MainScheduler.asyncInstance)
            
            .subscribe(onNext: { (text : String?) in
                print(text!)
                self.getCities(forCountryISO2Code: "LB", withQuery: text!)
            })
            .addDisposableTo(disposeBag)

```

**Comment by fpillet** [comment]
The compiler can't select the appropriate implementation of `distinct` because your observable's Elements are of type `String?` which is neither `Hashable` nor `Equatable`. You need to at least `map` the observable to `String` type, and you'll be all set.

**Comment by wassimseif** [comment]
can i unwrap it like this ?
```
 .map({ (string : String?) -> String in
                string!
            })
            .distinct()
            .observeOn(MainScheduler.asyncInstance)
            .subscribe({ (string ) in
                print(string.element!)
             })
```

**Comment by fpillet** [comment]
yes `.map ( $0! }` will do the job.
