### ISSUE TITLE
not() operator accessible by Driver instances

### ISSUE THREAD

**Issue by RafaelPlantard** [RxSwiftCommunity/RxSwiftExt#64]
### Name and description
Enable use of not() operator by Driver instances.

### Motivation for inclusion
It will be more simply invert a Driver<Bool> value:
Instead of:
```
viewModel.isShowResult.asObservable().not().asDriver(onErrorJustReturn: false).drive(tipButton.rx.isHighlighted)
            .addDisposableTo(disposeBag)
```

Just:
`viewModel.isShowResult.not().drive(tipButton.rx.isHighlighted).addDisposableTo(disposeBag)`

### Example of use
`viewModel.isShowResult.not().drive(tipButton.rx.isHighlighted).addDisposableTo(disposeBag)`

**Comment by fpillet** [comment]
Good idea! Do you think we should also make the other operators available on Driver?

**Comment by RafaelPlantard** [comment]
Sure!
