### ISSUE TITLE
Cut a 2.0.1 release for iOS 8 support

### ISSUE THREAD

**Issue by AndrewSB** [RxSwiftCommunity/RxSwiftExt#65]

**Comment by fpillet** [comment]
Uh ?

**Comment by AndrewSB** [comment]
Hey @fpillet, I was wondering if a new version of RxSwiftExt could be released that includes https://github.com/RxSwiftCommunity/RxSwiftExt/commit/1e1ce8e6f8bc998ee437b1d5da0a05af21762766  (updates RxSwiftExt to support back to iOS 8),  which was recently merged in

**Comment by fpillet** [comment]
Release 2.1.0 pushed to CP.
