### ISSUE TITLE
Support for RxSwift 3.1.0

### ISSUE THREAD

**Issue by acchou** [RxSwiftCommunity/RxSwiftExt#66]
### Name and description
RxSwift has released 3.1.0, but the podspec for RxSwiftExt specifies ~> 3.0.0.

### Motivation for inclusion
I'd like to use some of the functionality of RxSwift 3.1.0, specifically the improved UIBindingObserver behavior.

### Example of use
Hopefully this should be an easy fix. I'd be happy to add a PR to update the podspec, but I'm less sure what testing is needed before making this change. Happy to do it if given clear instructions...

**Comment by reloni** [comment]
It seems all works well with RxSwift 3.1.0. 
RxSwiftExt use carthage, and in cartfile version of RxSwift is not specified, it simply `github "ReactiveX/RxSwift"` (not sure that it's ok). I checked all unit tests against RxSwift 3.1.0 and there is no errors. So if you use carthage you can use latest versions of RxSwift and RxSwiftExt right now. Not sure about CocoaPods, don't know how it works:)

**Comment by acchou** [comment]
Thanks for checking that. I was referring to CocoaPods, which has the following line in the podspec file:

  s.dependency "RxSwift", '~> 3.0.0'

I think by changing that to 3.1.0 the issue would be resolved... I would be happy to submit a pull request, but I'm not sure of the process to build and test properly for CocoaPods...

**Comment by reloni** [comment]
I'm also not sure what we have to do with Pods, I think we should ask @fpillet for help:)

**Comment by AYastrebov** [comment]
s.dependency "RxSwift", '~> 3.0'

should resolve this issue

**Comment by freak4pc** [comment]
Yup, that's true. Submitting a PR for this.

**Comment by floskel** [comment]
Any progress on this?

**Comment by freak4pc** [comment]
Just needs a merge ... anyone can help ? @fpillet @ashfurrow

**Comment by fpillet** [comment]
Just merged, sorry I had missed the email for this issue

**Comment by dianambb** [comment]
This is still not working. Does this need to be updated in the Cocoapod repo as well? It shows the old dependancy:
https://github.com/CocoaPods/Specs/blob/master/Specs/b/0/1/RxSwiftExt/2.0.0/RxSwiftExt.podspec.json

**Comment by ashfurrow** [comment]
Yeah, likely needs a new version pushed, I'll try to get to it this afternoon 👍

**Comment by freak4pc** [comment]
Until the new spec is up you can change your dependncy to point straight to master.

**Comment by ashfurrow** [comment]
Should be up as 2.2.1, let us know how it goes :smile:

**Comment by dianambb** [comment]
@ashfurrow it looks like the Spec you push up was for Action and not RxSwiftExt- https://github.com/CocoaPods/Specs/commit/e8454bfc08a7840e8087ef07e2a5d385512fbb7a

The pod spec has not been updated in the repo.

@freak4pc Thanks. I shall do that.

**Comment by ashfurrow** [comment]
Ahhhh right, thanks 😅

**Comment by fpillet** [comment]
Too much going on at the same time, Ash! I'm taking care of this for RxSwiftExt 👍

**Comment by fpillet** [comment]
RxSwiftExt 2.1.0 pushed to CP. Thanks, all!
