### ISSUE TITLE
Materialize/Dematerialize operators

### ISSUE THREAD

**Issue by acchou** [RxSwiftCommunity/RxSwiftExt#67]
### Name and description
The materialize/dematerialize operators are described on the ReactiveX site here: http://reactivex.io/documentation/operators/materialize-dematerialize.html

I propose the following implementation, which uses Event<E> as the type of the materialized stream:

```Swift
extension ObservableType {
    public func materialize() -> Observable<Event<E>> {
        return Observable.create { observer in
            return self.subscribe { event in
                observer.onNext(event)
                if event.isStopEvent {
                    observer.onCompleted()
                }
            }
        }
    }
}

protocol EventConvertibleType {
    associatedtype E
    func asEvent() -> Event<E>
}

extension Event : EventConvertibleType {
    typealias E = Element
    func asEvent() -> Event<E> { return self }
}

extension ObservableType where E: EventConvertibleType {
    func dematerialize() -> Observable<E.E> {
        return Observable.create { observer in
            return self.subscribe(onNext: { event in
                switch event.asEvent() {
                case .next(let element): observer.onNext(element)
                case .error(let error): observer.onError(error)
                case .completed: observer.onCompleted()
                }
            })
        }
    }
    
    /// Return only the error events of an Observable<Event<E>>
    func errors() -> Observable<Error> {
        return self.filter { $0.asEvent().error != nil }
            .map { $0.asEvent().error! }
    }
    
    /// Return only the onNext element events of an Observable<Event<E>>
    func elements() -> Observable<E.E> {
        return self.filter { $0.asEvent().element != nil }
            .map { $0.asEvent().element! }
    }
}
```

### Motivation for inclusion

When reviewing the [Kickstarter](https://github.com/kickstarter/ios-oss) ios code base which was recently open sourced, I noticed this pattern for dealing with errors:

(from [LoginViewModels.swift:112](https://github.com/kickstarter/ios-oss/blob/master/Library/ViewModels/LoginViewModel.swift#L112):

```swift
    let loginEvent = emailAndPassword
      .takeWhen(tryLogin)
      .switchMap { email, password in
        AppEnvironment.current.apiService.login(email: email, password: password, code: nil)
          .materialize()
    }

    self.logIntoEnvironment = loginEvent.values()

    let tfaError = loginEvent.errors()
      .filter { $0.ksrCode == .TfaRequired }
      .ignoreValues()
```

Note that Kickstarter uses ReactiveCocoa, not RxSwift, so the operators are a bit different, but the core idea is the same. Using materialize is a convenient way to turn any Observable into a new observable where errors are just another kind of event.

By itself, this is not terribly exciting because plain Observables can return .next or .error as well. But combined with flatMap this can be very convenient because errors generated by the flatMap closure will not terminate the flatMap with an error.

The same thing can be accomplished by using an enum like Result<T> or a custom enum. But materialize/dematerialize is standardized by ReactiveX, and it does not require the user to create new custom data types.

### Example of use

Consider this example from the RxSwift documentation for [Units](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Units.md):

```swift
let results = query.rx.text
    .throttle(0.3, scheduler: MainScheduler.instance)
    .flatMapLatest { query in
        fetchAutoCompleteItems(query)
            .observeOn(MainScheduler.instance)  // results are returned on MainScheduler
            .catchErrorJustReturn([])           // in the worst case, errors are handled
    }
    .shareReplay(1)                             // HTTP requests are shared and results replayed
                                                // to all UI elements
```

Because `fetchAutoCompleteItems(query)` might fail, the use of `catchErrorJustReturn([])` is used to return an empty result. But in general failure might need to be handled in a different way, for example by popping up an alert, or doing some other action. While this could be done with a `do` operator, in general the actions could be complex and performing them here would complicate code in the common case and obscure the core logic.

Instead, we could materialize the results (this is kind of artificial so it is not necessarily recommended in this particular case, but the idea should stand):

```swift
let resultEvents = query.rx.text
    .throttle(0.3, scheduler: MainScheduler.instance)
    .flatMapLatest { query in
        fetchAutoCompleteItems(query)
            .observeOn(MainScheduler.instance)
            .materialize()          // now the results have type Event<[String]>
    }
    .shareReplay(1)

let results = resultEvents.elements()
let errors = resultEvents.errors()

// To get the results with empty results for errors, the same as the original code
let resultsWithEmptyErrors = Observable.of(results, errors.map { [] }).merge()

// Now we can process error events and show alerts, or perform other processing
errors.subscribe(onNext: { 
    log.error($0.localizedDescription)
    showAlert($0)
})
.addDisposableTo(disposeBag)
```

The `dematerialize` operator is here for completeness, though I don't have a compelling use case for it at the moment.

**Comment by fpillet** [comment]
This is great! I'm a big fan of `materialize` / `dematerialize` and I had been using them in several scenarios with RAC. I had struggled to tried an implementation, but failed.

I'm thrilled to add this to the code base. Please submit a PR with the following:
- the code for the operators themselves (a single file for both should suffices)
- tests
- if possible, add a page to the example playground

At a minimum, code & tests would be great. Tests are tedious to write but are here to guarantee that the operators behave properly in all cases.

Thanks for your contribution!

**Comment by acchou** [comment]
I was able to resolve this issue by using:

```
carthage bootstrap --platform ios --no-use-binaries
```

and building the regular RxSwiftExt scheme. I'm not sure if I should update the instructions in the playground files? For now I'm going to submit the PR without that change, we can discuss it.

**Comment by fpillet** [comment]
Hi Andy, thanks for the additional information! I'll take care of updating the playground instructions.

**Comment by fpillet** [comment]
Thanks a lot for this contribution!
