### ISSUE TITLE
Retry predicate is inverted when we pass in the error parameter

### ISSUE THREAD

**Issue by dianambb** [RxSwiftCommunity/RxSwiftExt#69]
### Retry predicate is inverted
In retryWithBehavior.swift, I see this in the retry function:
```
if let shouldRetry = shouldRetry, !shouldRetry(error) {
					// also return error if predicate says so
					return Observable.error(error)
				}
```
Why are we using  !shouldRetry(error) instead of  shouldRetry(error)?
It tends to be non-intuitive to return false for the error conditions I want to retry. Is this intentional or a bug?

**Comment by reloni** [comment]
Hello.
RetryPredicate is a function that user can provide to decide should we retry or not if specific error occurred. So, if shouldRetry(error) returns true, we don't return Observable.error(error) and do retry.
This is an example from playground:
```
example("Immediate retry with custom predicate") {
	// in this case we provide custom predicate, that will evaluate error and decide, should we retry or not
	_ = sampleObservable.retry(.immediate(maxCount: 3), scheduler: delayScheduler) { error in
		// error checks here
		// in this example we simply say, that retry not allowed
		return false
		}
		.subscribe(onNext: { event in
			print("Receive event: \(event)")
		}, onError: { error in
			print("Receive error \(error)")
		})
}
```
So, for conditions that user want to retry this predicate should return true.
