### ISSUE TITLE
Add Mac Framework

### ISSUE THREAD

**Issue by emorydunn** [RxSwiftCommunity/RxSwiftExt#75]
### Name and description
I'm working on a Mac application and would love to be able to use these extensions. RxSwiftExt doesn't use any iOS specific APIs and the all the tests pass on a macOS build. 

### Motivation for inclusion
Having a macOS build of the framework would help potentially dozens of Mac developers with handy Rx extensions. The bonus version of this would be to add a target for all of the platforms RxSwift has (iOS, macOS, watchOS, and tvOS).

**Comment by DivineDominion** [comment]
You need a hand on anything?

**Comment by fpillet** [comment]
Just checking since the Podspec allows Mac integration, is there anything else you need ?
