### ISSUE TITLE
Warnings with Xcode 8.3

### ISSUE THREAD

**Issue by dianambb** [RxSwiftCommunity/RxSwiftExt#79]
../Pods/RxSwiftExt/Source/cascade.swift:28:21: Static method should not be declared public because its generic requirement uses an internal type
../Pods/RxSwiftExt/Source/cascade.swift:14:12: Type declared here

**Comment by tzm41** [comment]
Same problem encountered.

**Comment by demchenkoalex** [comment]
Fixed in #80

**Comment by tzm41** [comment]
Great!

**Comment by fpillet** [comment]
Not fixed?

**Comment by dianambb** [comment]
We need an updated release with this change.

**Comment by fpillet** [comment]
On its way
