### ISSUE TITLE
Bring back errors() & elements() for materialized Observable

### ISSUE THREAD

**Issue by TheAdamBorek** [RxSwiftCommunity/RxSwiftExt#81]
### Name and description
Bring back `errors()` & `elements()` for materialized Observable

### Motivation for inclusion
`materialize()` was removed in latest (2.3.0) release of RxSwiftExt, as it's became a part of the core. However, RxSwiftExt used to offer 2 additional operators for materialized Observable which were very handy to use. The usage of them were to filter elements from errors.

I think it is a good idea to bring them back for 2 reasons:
1. it's very handy to have them
2. Stability of projects which use RxSwiftExt. Right now each project which updates RxSwiftExt to the newest version and had used `elements()`/`errors()` will stop to compile because of lack of these operators.

### Example of use
The usage is unchanged as it was in pre 2.3.0 releases:

```
        let imageResult = _chooseImageButtonPressed.asObservable()
            .flatMap { imageReceiver.image.materialize() }
            .share()
        
        image = imageResult
            .elements()
            .asDriver(onErrorDriveWith: .never())
        
        errorMessage = imageResult
            .errors()
            .map(mapErrorMessages)
            .unwrap()
            .asDriver(onErrorDriveWith: .never())
```

### Pull request
As soon as the issue will be accepted I will create a pull request with the changes ;)

**Comment by fpillet** [comment]
Hey Adam,

Thanks for taking care of this! It was an oversight, I hadn't noticed that I was actually deleting more than just the `materialize()` and `dematerizalize()` operators that @acchou kindly added.

Send the PR away :)

**Comment by reshadf** [comment]
This is still not working. The actual code is not inserted in the PR because I think it failed the tests.

**Comment by TheAdamBorek** [comment]
It's not because of tests ;) - @fpillet bumped the `.podspec` so everything is fine :)

This is probably the reason:
![zrzut ekranu 2017-04-14 13 47 21](https://cloud.githubusercontent.com/assets/3684577/25042526/06136216-2119-11e7-93ad-0fa37bc80f24.png)

The file is in wrong directory 😆 - I'll create a PR in a minute 😃
