### ISSUE TITLE
Carthage build fail in release 2.4.0

### ISSUE THREAD

**Issue by bidadh** [RxSwiftCommunity/RxSwiftExt#85]
I'm getting the following error with your latest release(2.4.0) using Carthage.
it was working before so I have to explicitly specify 2.2.0 in my Cartfile which is not my preferred way.

```
swift --version
Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)
Target: x86_64-apple-macosx10.9
```

`xcode 8.3.1`

**Building scheme "RxSwiftExt" in RxSwiftExt.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace PATH_TO_APP/Carthage/Checkouts/RxSwiftExt/RxSwiftExt.xcworkspace -scheme RxSwiftExt -configuration Release -derivedDataPath .../Library/Caches/org.carthage.CarthageKit/DerivedData/RxSwiftExt/2.4.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build**

build errors are:

materialized+elements.swift:10:35: error: use of undeclared type 'EventConvertible'
extension ObservableType where E: EventConvertible {
                                  ^~~~~~~~~~~~~~~~

aterialized+elements.swift:16:41: error: 'ElementType' is not a member type of 'Self.E'
        public func elements() -> Observable<E.ElementType> {
                                             ~ ^

materialized+elements.swift:26:34: error: ambiguous reference to member '!='
                return filter { $0.event.error != nil }
                                               ^~
Swift.!=:3:13: note: found this candidate
public func !=(t0: Any.Type?, t1: Any.Type?) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: UInt8, rhs: UInt8) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: Int8, rhs: Int8) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: UInt16, rhs: UInt16) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: Int16, rhs: Int16) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: UInt32, rhs: UInt32) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: Int32, rhs: Int32) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: UInt64, rhs: UInt64) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: Int64, rhs: Int64) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: UInt, rhs: UInt) -> Bool
            ^
Swift.!=:5:13: note: found this candidate
public func !=(lhs: Int, rhs: Int) -> Bool
            ^
Swift.!=:2:13: note: found this candidate
public func !=<Element>(lhs: ContiguousArray<Element>, rhs: ContiguousArray<Element>) -> Bool where Element : Equatable
            ^
Swift.!=:2:13: note: found this candidate
public func !=<Element>(lhs: ArraySlice<Element>, rhs: ArraySlice<Element>) -> Bool where Element : Equatable
            ^
Swift.!=:2:13: note: found this candidate
public func !=<Element>(lhs: [Element], rhs: [Element]) -> Bool where Element : Equatable
            ^
Swift.!=:6:13: note: found this candidate
public func !=<T>(lhs: T, rhs: T) -> Bool where T : RawRepresentable, T.RawValue : Equatable
            ^
Swift.!=:6:13: note: found this candidate
public func !=<T>(lhs: T, rhs: T) -> Bool where T : Equatable, T : RawRepresentable, T.RawValue : Equatable
            ^
Swift.!=:12:13: note: found this candidate
public func !=<T>(lhs: T, rhs: T) -> Bool where T : Equatable
            ^
Swift.!=:34:13: note: found this candidate
public func !=<T>(lhs: T?, rhs: T?) -> Bool where T : Equatable
            ^
Swift.!=:22:13: note: found this candidate
public func !=<T>(lhs: T?, rhs: _OptionalNilComparisonType) -> Bool
            ^
Swift.!=:22:13: note: found this candidate
public func !=<T>(lhs: _OptionalNilComparisonType, rhs: T?) -> Bool
            ^
Swift.!=:20:13: note: found this candidate
public func !=<A, B>(lhs: (A, B), rhs: (A, B)) -> Bool where A : Equatable, B : Equatable
            ^
Swift.!=:20:13: note: found this candidate
public func !=<A, B, C>(lhs: (A, B, C), rhs: (A, B, C)) -> Bool where A : Equatable, B : Equatable, C : Equatable
            ^
Swift.!=:20:13: note: found this candidate
public func !=<A, B, C, D>(lhs: (A, B, C, D), rhs: (A, B, C, D)) -> Bool where A : Equatable, B : Equatable, C : Equatable, D : Equatable
            ^
Swift.!=:20:13: note: found this candidate
public func !=<A, B, C, D, E>(lhs: (A, B, C, D, E), rhs: (A, B, C, D, E)) -> Bool where A : Equatable, B : Equatable, C : Equatable, D : Equatable, E : Equatable
            ^
Swift.!=:20:13: note: found this candidate
public func !=<A, B, C, D, E, F>(lhs: (A, B, C, D, E, F), rhs: (A, B, C, D, E, F)) -> Bool where A : Equatable, B : Equatable, C : Equatable, D : Equatable, E : Equatable, F : Equatable
            ^
Swift.LazyFilterIndex<Base>:3:24: note: found this candidate
    public static func !=(lhs: LazyFilterIndex<Base>, rhs: LazyFilterIndex<Base>) -> Bool
                       ^
Swift.Dictionary<Key, Value>:3:24: note: found this candidate
    public static func !=(lhs: [Key : Value], rhs: [Key : Value]) -> Bool
                       ^

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by fpillet** [comment]
2.4.1 release fixes this;

**Comment by bidadh** [comment]
Thanks @fpillet
