### ISSUE TITLE
Add RxCocoa.framework to Linked Frameworks

### ISSUE THREAD

**Issue by DanielAsher** [RxSwiftCommunity/RxSwiftExt#86]
### Name and description
I'm having trouble building `RxSwiftExt` with Carthage. I have included `RxSwiftExt` within my project as a dependent project, but noticed that it does not link to RxCocoa, although there are `import RxCocoa` dependencies within the source code.
### Motivation for inclusion
Explicitly link `RxCocoa` to allow for a build with Carthage

Please let me know if you would like a PR.

Thanks

**Comment by fpillet** [comment]
I looked at Carthage instructions but don't see a way to specify RxCocoa explicitely. Other frameworks like RxGesture which depend on RxCocoa seem to use the same Cartfile than we do here.

Would you mind sending out a PR for this? Thanks

**Comment by reloni** [comment]
I may be wrong, but this problem should be fixed after adding all necessary frameworks into build phase, as described in carthage docs:
![2017-06-25_18-57-43](https://user-images.githubusercontent.com/16653891/27517624-3f3e7a7e-59d8-11e7-880b-dd46427ab190.png)
