### ISSUE TITLE
elements() doesn't resolve from the framework, only source

### ISSUE THREAD

**Issue by kamitchell** [RxSwiftCommunity/RxSwiftExt#89]
Thanks for these extensions. I'm using them to work with materialized events for calculations that can fail, but shouldn't cancel the sequence.

Xcode 8.3.2
RxSwiftExt 2.4.1

Using 

```
carthage update --platform iOS --no-use-binaries --cache-builds
```

And then I insert the framework according to instructions.

I'm getting the following error:

```
/Users/kevin/src/.../ViewModels/something.swift:66:14: error: value of type 'Observable<Event<Double>>' has no member 'elements'
            .map { $0.tuplename1 }
~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
```

(the next line is ``.elements()``) (file and identifier names have been changed for nondisclosure)

Obviously, `Observable<Event<Double>>` should be the correct type for extension with `.elements()`, even according to the error message.

So far I've tried cleaning the project, rebuilding all Carthage frameworks, and removing the DerivedData directory.

I know the methods are there:

```
nm Carthage/Build/iOS/RxSwiftExt.framework/RxSwiftExt | grep elements
000000000000c130 t __TFFe10RxSwiftExtRx7RxSwift14ObservableTypewx1ES0_16EventConvertiblerS1_8elementsFT_GCS0_10ObservableWxS2_11ElementType__U0_FwxS2_WxS2_S5__
000000000000bf30 t __TFFe10RxSwiftExtRx7RxSwift14ObservableTypewx1ES0_16EventConvertiblerS1_8elementsFT_GCS0_10ObservableWxS2_11ElementType__U_FwxS2_Sb
000000000000be40 T __TFe10RxSwiftExtRx7RxSwift14ObservableTypewx1ES0_16EventConvertiblerS1_8elementsfT_GCS0_10ObservableWxS2_11ElementType__
000000000000c2c0 t __TPA__TFFe10RxSwiftExtRx7RxSwift14ObservableTypewx1ES0_16EventConvertiblerS1_8elementsFT_GCS0_10ObservableWxS2_11ElementType__U0_FwxS2_WxS2_S5__
000000000000c0f0 t __TPA__TFFe10RxSwiftExtRx7RxSwift14ObservableTypewx1ES0_16EventConvertiblerS1_8elementsFT_GCS0_10ObservableWxS2_11ElementType__U_FwxS2_Sb
```

But what's really strange is that if I remove the RxSwiftExt framework from my project, and put in the RxSwiftExt _sources_ from `Carthage/Checkouts`, it works.

Any ideas?

**Comment by fpillet** [comment]
I don't specifically use Carthage, although this ought to work -- it looks like the framework is just not linked into your Xcode project. How did you add it ?

**Comment by reloni** [comment]
@kamitchell I know that it's silly question, but did you add `import RxSwiftExt` into your swift file?
