### ISSUE TITLE
Adding mapElements operator

### ISSUE THREAD

**Issue by TheAdamBorek** [RxSwiftCommunity/RxSwiftExt#93]
## Adding `mapElements` operator

In every project where I use RxSwift I always end up with adding small helper for mapping elements inside the array in `Observable<[Type]>`. Maybe it's time to include it into one library with common, additional Rx operators ;)

### Motivation for inclusion

My motivation is simple. This... :
```swift
theObservable
  .mapElements(TheModel.init)
```

is more readable than... :

```swift
theObservable
 .map { array: in 
   return array.map(TheModel.init)
}
```

### Example of use
Example can be found just above ;)

**Comment by mosamer** [comment]
I may also suggest adding `filterElements` operator

**Comment by jdisho** [comment]
What do you think about this @freak4pc ?

**Comment by freak4pc** [comment]
Totally missed this one, thanks for the bump @jdisho. I think this could be a nice addition potentially, just want to make sure I got you correctly.

Are you looking for something like this @TheAdamBorek : 

```swift
extension ObservableType where E: Collection {
  func mapMany<R>(_ transform: @escaping (E.Element) throws -> R) -> Observable<[R]> {
    return map { collection in
      try collection.map(transform)
    }
  }
}
```

Usage: 
```swift
struct Thing: CustomStringConvertible {
  let number: Int
  init(number: Int) {
    self.number = number
  }

  var description: String { return "#\(number)" }
}

Observable.of([1, 2, 3, 4])
  .mapMany(Thing.init)
```

Output:
`-> Event next([#1, #2, #3, #4])`

**Comment by jdisho** [comment]
Why calling it `mapMany` @freak4pc? I think `mapElements` is more clear.

**Comment by freak4pc** [comment]
I'm personally not a fan of `mapElements`, since the original operator isn't called `MapElement` in singular... 

When you map emissions coming from an observable stream you are also `mapping elements` so I don't think this creates a proper "plural" distinction (e.g. this works only on `Collection` types)

We can put it up for a vote of names like we did in #150

**Comment by TheAdamBorek** [comment]
To be honest, I also like `mapMany` more than `mapElementes` (since Observable already has elements) ;)

However, the PR is quite old. I assume I would have to update it, right?

**Comment by TheAdamBorek** [comment]
@jdisho sure, go ahead ;

**Comment by freak4pc** [comment]
Let's continue discussion over at #154 :)
