### ISSUE TITLE
weak map oprator

### ISSUE THREAD

**Issue by noppefoxwolf** [RxSwiftCommunity/RxSwiftExt#99]
### Name and description

`map(weak:selector:)` is convenience map oprator.

```swift
public extension ObservableType {
  public func map<A: AnyObject, R>(weak obj: A, selector: @escaping (A, Self.E) throws -> R) -> Observable<R> {
    return flatMap { [weak obj] (value) -> Observable<R> in
      obj.map { (obj) in
        self.map({ _ in try selector(obj, value) })
      } ?? .empty()
    }
  }
}
```

### Motivation for inclusion

When using self in the map operator, we need to write a `[weak self]` clause every time.
like this,

```
button.rx.tap.map({ [weak self] _ in self?.textView.text }).bind(to: publishText).disposed(by: bag)
```

### Example of use

```
button.rx.tap.map(weak: textView, selector: { $0.text }).bind(to: publishText).disposed(by: bag)
```

**Comment by noppefoxwolf** [comment]
Can anyone put on the `proposed Operator` label?
I did not have that permissions.

**Comment by freak4pc** [comment]
I'm not sure I follow the motivation for this operator. 
It sort of couples the UI to the RxSwift layer which doesn't seem correct to have an operator for. 

It seems to me the most common use case would be inside a ViewModel mapping the input of a tap to some output Observable that would drive the View. 

Your operator seems to be needed when the entire Rx logic lives inside the ViewController which doesn't seem like best practice or anything RxSwift would want to educate people on doing. 

If i'm totally missing your intent here can you explain the use case? 

Thanks !

**Comment by noppefoxwolf** [comment]
I think your opinion is correct.
When I review this propose, I noticed that it broke the shape of MVVM.
Thank you for your feedback!!
I'll close this issue.
